.TH "/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/web Directory Reference" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/web Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgoogle\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgeo\&.php\fP"
.br
.ti -1c
.RI "file \fBoauth2\&.php\fP"
.br
.ti -1c
.RI "file \fBopenid\&.php\fP"
.br
.ti -1c
.RI "file \fBpingback\&.php\fP"
.br
.in -1c
