.TH "/Users/aplennevaux/GITHUB/Visionary-website Directory Reference" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
