.TH "Audit" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audit \- Data validator\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrefab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBurl\fP ($str)"
.br
.ti -1c
.RI "\fBemail\fP ($str, $mx=TRUE)"
.br
.ti -1c
.RI "\fBipv4\fP ($addr)"
.br
.ti -1c
.RI "\fBipv6\fP ($addr)"
.br
.ti -1c
.RI "\fBisprivate\fP ($addr)"
.br
.ti -1c
.RI "\fBisreserved\fP ($addr)"
.br
.ti -1c
.RI "\fBispublic\fP ($addr)"
.br
.ti -1c
.RI "\fBisdesktop\fP ($agent=NULL)"
.br
.ti -1c
.RI "\fBismobile\fP ($agent=NULL)"
.br
.ti -1c
.RI "\fBisbot\fP ($agent=NULL)"
.br
.ti -1c
.RI "\fBmod10\fP ($id)"
.br
.ti -1c
.RI "\fBcard\fP ($id)"
.br
.ti -1c
.RI "\fBentropy\fP ($str)"
.br
.in -1c
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const \fBUA_Mobile\fP ='android|blackberry|phone|ipod|palm|windows\\s+ce'"
.br
.ti -1c
.RI "const \fBUA_Desktop\fP ='bsd|linux|os\\s+[x9]|solaris|windows'"
.br
.ti -1c
.RI "const \fBUA_Bot\fP ='bot|crawl|slurp|spider'"
.br
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Data validator\&. 
.PP
Definition at line 24 of file audit\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "card ( $id)"
Return credit card type if number is valid 
.PP
\fBReturns:\fP
.RS 4
string|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.RE
.PP

.PP
Definition at line 158 of file audit\&.php\&.
.SS "email ( $str,  $mx = \fCTRUE\fP)"
Return TRUE if string is a valid e-mail address; Check DNS MX records if specified 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.br
\fI$mx\fP boolean 
.RE
.PP

.PP
Definition at line 49 of file audit\&.php\&.
.SS "entropy ( $str)"
Return entropy estimate of a password (NIST 800-63) 
.PP
\fBReturns:\fP
.RS 4
int|float 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 183 of file audit\&.php\&.
.SS "ipv4 ( $addr)"
Return TRUE if string is a valid IPV4 address 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$addr\fP string 
.RE
.PP

.PP
Definition at line 60 of file audit\&.php\&.
.SS "ipv6 ( $addr)"
Return TRUE if string is a valid IPV6 address 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$addr\fP string 
.RE
.PP

.PP
Definition at line 69 of file audit\&.php\&.
.SS "isbot ( $agent = \fCNULL\fP)"
Return TRUE if user agent is a \fBWeb\fP bot 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$agent\fP string 
.RE
.PP

.PP
Definition at line 132 of file audit\&.php\&.
.SS "isdesktop ( $agent = \fCNULL\fP)"
Return TRUE if user agent is a desktop browser 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$agent\fP string 
.RE
.PP

.PP
Definition at line 109 of file audit\&.php\&.
.SS "ismobile ( $agent = \fCNULL\fP)"
Return TRUE if user agent is a mobile device 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$agent\fP string 
.RE
.PP

.PP
Definition at line 121 of file audit\&.php\&.
.SS "isprivate ( $addr)"
Return TRUE if IP address is within private range 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$addr\fP string 
.RE
.PP

.PP
Definition at line 78 of file audit\&.php\&.
.SS "ispublic ( $addr)"
Return TRUE if IP address is neither private nor reserved 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$addr\fP string 
.RE
.PP

.PP
Definition at line 98 of file audit\&.php\&.
.SS "isreserved ( $addr)"
Return TRUE if IP address is within reserved range 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$addr\fP string 
.RE
.PP

.PP
Definition at line 88 of file audit\&.php\&.
.SS "mod10 ( $id)"
Return TRUE if specified ID has a valid (Luhn) Mod-10 check digit 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.RE
.PP

.PP
Definition at line 143 of file audit\&.php\&.
.SS "url ( $str)"
Return TRUE if string is a valid URL 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 38 of file audit\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const UA_Bot ='bot|crawl|slurp|spider'"

.PP
Definition at line 30 of file audit\&.php\&.
.SS "const UA_Desktop ='bsd|linux|os\\s+[x9]|solaris|windows'"

.PP
Definition at line 29 of file audit\&.php\&.
.SS "const UA_Mobile ='android|blackberry|phone|ipod|palm|windows\\s+ce'"

.PP
Definition at line 28 of file audit\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
