.TH "Auth" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Auth \- Authorization/authentication plug-in\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlogin\fP ($id, $pw, $realm=NULL)"
.br
.ti -1c
.RI "\fBbasic\fP ($func=NULL)"
.br
.ti -1c
.RI "\fB__construct\fP ($storage, array $args=NULL)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$mapper\fP"
.br
.RI "Mapper object\&. "
.ti -1c
.RI "\fB$args\fP"
.br
.RI "Storage options\&. "
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const \fBE_LDAP\fP ='LDAP connection failure'"
.br
.ti -1c
.RI "const \fBE_SMTP\fP ='\fBSMTP\fP connection failure'"
.br
.in -1c
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_jig\fP ($id, $pw, $realm)"
.br
.ti -1c
.RI "\fB_mongo\fP ($id, $pw, $realm)"
.br
.ti -1c
.RI "\fB_sql\fP ($id, $pw, $realm)"
.br
.ti -1c
.RI "\fB_ldap\fP ($id, $pw)"
.br
.ti -1c
.RI "\fB_smtp\fP ($id, $pw)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$storage\fP"
.br
.RI "\fBAuth\fP storage\&. "
.in -1c
.SH "Detailed Description"
.PP 
Authorization/authentication plug-in\&. 
.PP
Definition at line 24 of file auth\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $storage, array $args = \fCNULL\fP)"
Instantiate class 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$storage\fP string|object 
.br
\fI$args\fP array 
.RE
.PP

.PP
Definition at line 229 of file auth\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "_jig ( $id,  $pw,  $realm)\fC [protected]\fP"
Jig storage handler 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$pw\fP string 
.br
\fI$realm\fP string 
.RE
.PP

.PP
Definition at line 47 of file auth\&.php\&.
.SS "_ldap ( $id,  $pw)\fC [protected]\fP"
LDAP storage handler 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$pw\fP string 
.RE
.PP

.PP
Definition at line 117 of file auth\&.php\&.
.SS "_mongo ( $id,  $pw,  $realm)\fC [protected]\fP"
MongoDB storage handler 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$pw\fP string 
.br
\fI$realm\fP string 
.RE
.PP

.PP
Definition at line 73 of file auth\&.php\&.
.SS "_smtp ( $id,  $pw)\fC [protected]\fP"
\fBSMTP\fP storage handler 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$pw\fP string 
.RE
.PP

.PP
Definition at line 140 of file auth\&.php\&.
.SS "_sql ( $id,  $pw,  $realm)\fC [protected]\fP"
SQL storage handler 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$pw\fP string 
.br
\fI$realm\fP string 
.RE
.PP

.PP
Definition at line 92 of file auth\&.php\&.
.SS "basic ( $func = \fCNULL\fP)"
HTTP basic auth mechanism 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 197 of file auth\&.php\&.
.SS "login ( $id,  $pw,  $realm = \fCNULL\fP)"
Login auth mechanism 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$pw\fP string 
.br
\fI$realm\fP string 
.RE
.PP

.PP
Definition at line 188 of file auth\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$args"

.PP
Storage options\&. 
.PP
Definition at line 34 of file auth\&.php\&.
.SS "$mapper"

.PP
Mapper object\&. 
.PP
Definition at line 34 of file auth\&.php\&.
.SS "$storage\fC [protected]\fP"

.PP
\fBAuth\fP storage\&. 
.PP
Definition at line 34 of file auth\&.php\&.
.SS "const E_LDAP ='LDAP connection failure'"

.PP
Definition at line 28 of file auth\&.php\&.
.SS "const E_SMTP ='\fBSMTP\fP connection failure'"

.PP
Definition at line 29 of file auth\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
