.TH "/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/base.php" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/base.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPrefab\fP"
.br
.RI "Factory class for single-instance objects\&. "
.ti -1c
.RI "class \fBBase\fP"
.br
.RI "\fBBase\fP structure\&. "
.ti -1c
.RI "class \fBCache\fP"
.br
.RI "\fBCache\fP engine\&. "
.ti -1c
.RI "class \fBView\fP"
.br
.RI "\fBView\fP handler\&. "
.ti -1c
.RI "class \fBPreview\fP"
.br
.RI "Lightweight template engine\&. "
.ti -1c
.RI "class \fBISO\fP"
.br
.RI "\fBISO\fP language/country codes\&. "
.ti -1c
.RI "class \fBRegistry\fP"
.br
.RI "Container for singular object instances\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
