.TH "Basket" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Basket \- Session-based pseudo-mapper\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMagic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexists\fP ($key)"
.br
.ti -1c
.RI "\fBset\fP ($key, $val)"
.br
.ti -1c
.RI "& \fBget\fP ($key)"
.br
.ti -1c
.RI "\fBclear\fP ($key)"
.br
.ti -1c
.RI "\fBfind\fP ($key=NULL, $val=NULL)"
.br
.ti -1c
.RI "\fBfindone\fP ($key, $val)"
.br
.ti -1c
.RI "\fBload\fP ($key, $val)"
.br
.ti -1c
.RI "\fBdry\fP ()"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.ti -1c
.RI "\fBsave\fP ()"
.br
.ti -1c
.RI "\fBerase\fP ($key, $val)"
.br
.ti -1c
.RI "\fBreset\fP ()"
.br
.ti -1c
.RI "\fBdrop\fP ()"
.br
.ti -1c
.RI "\fBcopyfrom\fP ($var)"
.br
.ti -1c
.RI "\fBcopyto\fP ($key)"
.br
.ti -1c
.RI "\fBcheckout\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ($key='basket')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.RI "Current item identifier\&. "
.ti -1c
.RI "\fB$item\fP =[]"
.br
.RI "Current item contents\&. "
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const \fBE_Field\fP ='Undefined field %s'"
.br
.in -1c
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$key\fP"
.br
.RI "\fBSession\fP key\&. "
.in -1c
.SH "Detailed Description"
.PP 
Session-based pseudo-mapper\&. 
.PP
Definition at line 24 of file basket\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $key = \fC'basket'\fP)"
Instantiate class 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 230 of file basket\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "checkout ()"
Check out basket contents 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 216 of file basket\&.php\&.
.SS "clear ( $key)"
Delete field 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 77 of file basket\&.php\&.
.SS "copyfrom ( $var)"
Hydrate item using hive array variable 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array|string 
.RE
.PP

.PP
Definition at line 194 of file basket\&.php\&.
.SS "copyto ( $key)"
Populate hive array variable with item contents 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 206 of file basket\&.php\&.
.SS "count ()"
Return number of items in basket 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 140 of file basket\&.php\&.
.SS "drop ()"
Empty basket 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP

.PP
Definition at line 185 of file basket\&.php\&.
.SS "dry ()"
Return TRUE if current item is empty/undefined 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 132 of file basket\&.php\&.
.SS "erase ( $key,  $val)"
Erase item matching key/value pair 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP mixed 
.RE
.PP

.PP
Definition at line 161 of file basket\&.php\&.
.SS "exists ( $key)"
Return TRUE if field is defined 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 44 of file basket\&.php\&.
.SS "find ( $key = \fCNULL\fP,  $val = \fCNULL\fP)"
Return items that match key/value pair; If no key/value pair specified, return all items 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP mixed 
.RE
.PP

.PP
Definition at line 88 of file basket\&.php\&.
.SS "findone ( $key,  $val)"
Return first item that matches key/value pair 
.PP
\fBReturns:\fP
.RS 4
object|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP mixed 
.RE
.PP

.PP
Definition at line 109 of file basket\&.php\&.
.SS "& get ( $key)"
Retrieve value of field 
.PP
\fBReturns:\fP
.RS 4
scalar|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 63 of file basket\&.php\&.
.SS "load ( $key,  $val)"
Map current item to matching key/value pair 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP mixed 
.RE
.PP

.PP
Definition at line 119 of file basket\&.php\&.
.SS "reset ()"
Reset cursor 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP

.PP
Definition at line 176 of file basket\&.php\&.
.SS "save ()"
Save current item 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 148 of file basket\&.php\&.
.SS "set ( $key,  $val)"
Assign value to field 
.PP
\fBReturns:\fP
.RS 4
scalar|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP scalar 
.RE
.PP

.PP
Definition at line 54 of file basket\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$id"

.PP
Current item identifier\&. 
.PP
Definition at line 33 of file basket\&.php\&.
.SS "$item =[]"

.PP
Current item contents\&. 
.PP
Definition at line 37 of file basket\&.php\&.
.SS "$key\fC [protected]\fP"

.PP
\fBSession\fP key\&. 
.PP
Definition at line 33 of file basket\&.php\&.
.SS "const E_Field ='Undefined field %s'"

.PP
Definition at line 28 of file basket\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
