.TH "Cache" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache \- \fBCache\fP engine\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrefab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexists\fP ($key, &$val=NULL)"
.br
.ti -1c
.RI "\fBset\fP ($key, $val, $ttl=0)"
.br
.ti -1c
.RI "\fBget\fP ($key)"
.br
.ti -1c
.RI "\fBclear\fP ($key)"
.br
.ti -1c
.RI "\fBreset\fP ($suffix=NULL, $lifetime=0)"
.br
.ti -1c
.RI "\fBload\fP ($dsn)"
.br
.ti -1c
.RI "\fB__construct\fP ($dsn=FALSE)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$prefix\fP"
.br
.RI "Prefix for cache entries\&. "
.ti -1c
.RI "\fB$ref\fP"
.br
.RI "MemCache or Redis object\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$dsn\fP"
.br
.RI "\fBCache\fP DSN\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBCache\fP engine\&. 
.PP
Definition at line 2345 of file base\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $dsn = \fCFALSE\fP)"
Class constructor 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$dsn\fP bool|string 
.RE
.PP

.PP
Definition at line 2588 of file base\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "clear ( $key)"
Delete cache entry 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 2447 of file base\&.php\&.
.SS "exists ( $key, & $val = \fCNULL\fP)"
Return timestamp and TTL of cache entry or FALSE if not found 
.PP
\fBReturns:\fP
.RS 4
array|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP mixed 
.RE
.PP

.PP
Definition at line 2361 of file base\&.php\&.
.SS "get ( $key)"
Retrieve value of cache entry 
.PP
\fBReturns:\fP
.RS 4
mixed|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 2438 of file base\&.php\&.
.SS "load ( $dsn)"
Load/auto-detect cache backend 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$dsn\fP bool|string 
.RE
.PP

.PP
Definition at line 2547 of file base\&.php\&.
.SS "reset ( $suffix = \fCNULL\fP,  $lifetime = \fC0\fP)"
Clear contents of cache backend 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$suffix\fP string 
.br
\fI$lifetime\fP int 
.RE
.PP

.PP
Definition at line 2476 of file base\&.php\&.
.SS "set ( $key,  $val,  $ttl = \fC0\fP)"
Store value in cache 
.PP
\fBReturns:\fP
.RS 4
mixed|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP mixed 
.br
\fI$ttl\fP int 
.RE
.PP

.PP
Definition at line 2405 of file base\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$dsn\fC [protected]\fP"

.PP
\fBCache\fP DSN\&. 
.PP
Definition at line 2349 of file base\&.php\&.
.SS "$prefix"

.PP
Prefix for cache entries\&. 
.PP
Definition at line 2349 of file base\&.php\&.
.SS "$ref"

.PP
MemCache or Redis object\&. 
.PP
Definition at line 2349 of file base\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
