.TH "DB" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBJig\fP"
.br
.ti -1c
.RI " \fBMongo\fP"
.br
.ti -1c
.RI " \fBSQL\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCursor\fP"
.br
.RI "Simple cursor implementation\&. "
.ti -1c
.RI "class \fBJig\fP"
.br
.RI "In-memory/flat-file \fBDB\fP wrapper\&. "
.ti -1c
.RI "class \fBMongo\fP"
.br
.RI "MongoDB wrapper\&. "
.ti -1c
.RI "class \fBSQL\fP"
.br
.RI "PDO wrapper\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
