.TH "Cursor" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cursor \- Simple cursor implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMagic\fP, and IteratorAggregate\&.
.PP
Inherited by \fBMapper\fP, \fBMapper\fP, and \fBMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdbtype\fP ()"
.br
.ti -1c
.RI "\fBfields\fP ()"
.br
.ti -1c
.RI "\fBcast\fP ($obj=NULL)"
.br
.ti -1c
.RI "\fBfind\fP ($filter=NULL, array $options=NULL, $ttl=0)"
.br
.ti -1c
.RI "\fBcount\fP ($filter=NULL, $ttl=0)"
.br
.ti -1c
.RI "\fBinsert\fP ()"
.br
.ti -1c
.RI "\fBupdate\fP ()"
.br
.ti -1c
.RI "\fBcopyfrom\fP ($var, $func=NULL)"
.br
.ti -1c
.RI "\fBcopyto\fP ($key)"
.br
.ti -1c
.RI "\fBgetiterator\fP ()"
.br
.ti -1c
.RI "\fBdry\fP ()"
.br
.ti -1c
.RI "\fBfindone\fP ($filter=NULL, array $options=NULL, $ttl=0)"
.br
.ti -1c
.RI "\fBpaginate\fP ( $pos=0, $size=10, $filter=NULL, array $options=NULL, $ttl=0)"
.br
.ti -1c
.RI "\fBload\fP ($filter=NULL, array $options=NULL, $ttl=0)"
.br
.ti -1c
.RI "\fBloaded\fP ()"
.br
.ti -1c
.RI "\fBfirst\fP ()"
.br
.ti -1c
.RI "\fBlast\fP ()"
.br
.ti -1c
.RI "\fBskip\fP ($ofs=1)"
.br
.ti -1c
.RI "\fBnext\fP ()"
.br
.ti -1c
.RI "\fBprev\fP ()"
.br
.ti -1c
.RI "\fBvalid\fP ()"
.br
.ti -1c
.RI "\fBsave\fP ()"
.br
.ti -1c
.RI "\fBerase\fP ()"
.br
.ti -1c
.RI "\fBonload\fP ($func)"
.br
.ti -1c
.RI "\fBbeforeinsert\fP ($func)"
.br
.ti -1c
.RI "\fBafterinsert\fP ($func)"
.br
.ti -1c
.RI "\fBoninsert\fP ($func)"
.br
.ti -1c
.RI "\fBbeforeupdate\fP ($func)"
.br
.ti -1c
.RI "\fBafterupdate\fP ($func)"
.br
.ti -1c
.RI "\fBonupdate\fP ($func)"
.br
.ti -1c
.RI "\fBbeforesave\fP ($func)"
.br
.ti -1c
.RI "\fBaftersave\fP ($func)"
.br
.ti -1c
.RI "\fBonsave\fP ($func)"
.br
.ti -1c
.RI "\fBbeforeerase\fP ($func)"
.br
.ti -1c
.RI "\fBaftererase\fP ($func)"
.br
.ti -1c
.RI "\fBonerase\fP ($func)"
.br
.ti -1c
.RI "\fBreset\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$ptr\fP =0"
.br
.RI "Current position\&. "
.ti -1c
.RI "\fB$trigger\fP =[]"
.br
.RI "Event listeners\&. "
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const \fBE_Field\fP ='Undefined field %s'"
.br
.in -1c
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$query\fP =[]"
.br
.RI "Query results\&. "
.in -1c
.SH "Detailed Description"
.PP 
Simple cursor implementation\&. 
.PP
Definition at line 26 of file cursor\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "aftererase ( $func)"
Define aftererase trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 363 of file cursor\&.php\&.
.SS "afterinsert ( $func)"
Define afterinsert trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 278 of file cursor\&.php\&.
.SS "aftersave ( $func)"
Define aftersave trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 334 of file cursor\&.php\&.
.SS "afterupdate ( $func)"
Define afterupdate trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 305 of file cursor\&.php\&.
.SS "beforeerase ( $func)"
Define beforeerase trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 354 of file cursor\&.php\&.
.SS "beforeinsert ( $func)"
Define beforeinsert trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 269 of file cursor\&.php\&.
.SS "beforesave ( $func)"
Define beforesave trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 323 of file cursor\&.php\&.
.SS "beforeupdate ( $func)"
Define beforeupdate trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 296 of file cursor\&.php\&.
.SS "cast ( $obj = \fCNULL\fP)\fC [abstract]\fP"
Return fields of mapper object as an associative array 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$obj\fP object 
.RE
.PP

.SS "copyfrom ( $var,  $func = \fCNULL\fP)\fC [abstract]\fP"
Hydrate mapper object using hive array variable 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array|string 
.br
\fI$func\fP callback 
.RE
.PP

.SS "copyto ( $key)\fC [abstract]\fP"
Populate hive array variable with mapper fields 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.SS "count ( $filter = \fCNULL\fP,  $ttl = \fC0\fP)\fC [abstract]\fP"
Count records that match criteria 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP array 
.br
\fI$ttl\fP int 
.RE
.PP

.SS "dbtype ()\fC [abstract]\fP"
Return database type 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "dry ()"
Return TRUE if current cursor position is not mapped to any record 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 116 of file cursor\&.php\&.
.SS "erase ()"
Delete current record 
.PP
\fBReturns:\fP
.RS 4
int|bool 
.RE
.PP

.PP
Definition at line 249 of file cursor\&.php\&.
.SS "fields ()\fC [abstract]\fP"
Return field names 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "find ( $filter = \fCNULL\fP, array $options = \fCNULL\fP,  $ttl = \fC0\fP)\fC [abstract]\fP"
Return records (array of mapper objects) that match criteria 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP string|array 
.br
\fI$options\fP array 
.br
\fI$ttl\fP int 
.RE
.PP

.SS "findone ( $filter = \fCNULL\fP, array $options = \fCNULL\fP,  $ttl = \fC0\fP)"
Return first record (mapper object) that matches criteria 
.PP
\fBReturns:\fP
.RS 4
static|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP string|array 
.br
\fI$options\fP array 
.br
\fI$ttl\fP int 
.RE
.PP

.PP
Definition at line 127 of file cursor\&.php\&.
.SS "first ()"
Map to first record in cursor 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 191 of file cursor\&.php\&.
.SS "getiterator ()\fC [abstract]\fP"
Get cursor's equivalent external iterator Causes a fatal error in PHP 5\&.3\&.5 if uncommented return ArrayIterator 
.SS "insert ()\fC [abstract]\fP"
Insert new record 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "last ()"
Map to last record in cursor 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 199 of file cursor\&.php\&.
.SS "load ( $filter = \fCNULL\fP, array $options = \fCNULL\fP,  $ttl = \fC0\fP)"
Map to first record that matches criteria 
.PP
\fBReturns:\fP
.RS 4
array|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP string|array 
.br
\fI$options\fP array 
.br
\fI$ttl\fP int 
.RE
.PP

.PP
Definition at line 173 of file cursor\&.php\&.
.SS "loaded ()"
Return the count of records loaded 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 183 of file cursor\&.php\&.
.SS "next ()"
Map next record 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 218 of file cursor\&.php\&.
.SS "onerase ( $func)"
Define onerase trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 372 of file cursor\&.php\&.
.SS "oninsert ( $func)"
Define oninsert trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 287 of file cursor\&.php\&.
.SS "onload ( $func)"
Define onload trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 260 of file cursor\&.php\&.
.SS "onsave ( $func)"
Define onsave trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 345 of file cursor\&.php\&.
.SS "onupdate ( $func)"
Define onupdate trigger 
.PP
\fBReturns:\fP
.RS 4
callback 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 314 of file cursor\&.php\&.
.SS "paginate ( $pos = \fC0\fP,  $size = \fC10\fP,  $filter = \fCNULL\fP, array $options = \fCNULL\fP,  $ttl = \fC0\fP)"
Return array containing subset of records matching criteria, total number of records in superset, specified limit, number of subsets available, and actual subset position 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$pos\fP int 
.br
\fI$size\fP int 
.br
\fI$filter\fP string|array 
.br
\fI$options\fP array 
.br
\fI$ttl\fP int 
.RE
.PP

.PP
Definition at line 146 of file cursor\&.php\&.
.SS "prev ()"
Map previous record 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 226 of file cursor\&.php\&.
.SS "reset ()"
Reset cursor 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP

.PP
Definition at line 380 of file cursor\&.php\&.
.SS "save ()"
Save mapped record 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 241 of file cursor\&.php\&.
.SS "skip ( $ofs = \fC1\fP)"
Map to nth record relative to current cursor position 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$ofs\fP int 
.RE
.PP

.PP
Definition at line 208 of file cursor\&.php\&.
.SS "update ()\fC [abstract]\fP"
Update current record 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "valid ()"
Return whether current iterator position is valid\&. 
.PP
Definition at line 233 of file cursor\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$ptr =0"

.PP
Current position\&. 
.PP
Definition at line 37 of file cursor\&.php\&.
.SS "$query =[]\fC [protected]\fP"

.PP
Query results\&. 
.PP
Definition at line 35 of file cursor\&.php\&.
.SS "$trigger =[]"

.PP
Event listeners\&. 
.PP
Definition at line 39 of file cursor\&.php\&.
.SS "const E_Field ='Undefined field %s'"

.PP
Definition at line 30 of file cursor\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
