.TH "DB\Jig" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB\Jig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMapper\fP"
.br
.RI "Flat-file \fBDB\fP mapper\&. "
.ti -1c
.RI "class \fBSession\fP"
.br
.RI "Jig-managed session handler\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
