.TH "Mapper" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mapper \- Flat-file \fBDB\fP mapper\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCursor\fP\&.
.PP
Inherited by \fBSession\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdbtype\fP ()"
.br
.ti -1c
.RI "\fBexists\fP ($key)"
.br
.ti -1c
.RI "\fBset\fP ($key, $val)"
.br
.ti -1c
.RI "& \fBget\fP ($key)"
.br
.ti -1c
.RI "\fBclear\fP ($key)"
.br
.ti -1c
.RI "\fBcast\fP ($obj=NULL)"
.br
.ti -1c
.RI "\fBtoken\fP ($str)"
.br
.ti -1c
.RI "\fBfind\fP ($filter=NULL, array $options=NULL, $ttl=0, $\fBlog\fP=TRUE)"
.br
.ti -1c
.RI "\fBcount\fP ($filter=NULL, $ttl=0)"
.br
.ti -1c
.RI "\fBskip\fP ($ofs=1)"
.br
.ti -1c
.RI "\fBinsert\fP ()"
.br
.ti -1c
.RI "\fBupdate\fP ()"
.br
.ti -1c
.RI "\fBerase\fP ($filter=NULL)"
.br
.ti -1c
.RI "\fBreset\fP ()"
.br
.ti -1c
.RI "\fBcopyfrom\fP ($var, $func=NULL)"
.br
.ti -1c
.RI "\fBcopyto\fP ($key)"
.br
.ti -1c
.RI "\fBfields\fP ()"
.br
.ti -1c
.RI "\fBgetiterator\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP (\\\fBDB\\Jig\fP $db, $file)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$file\fP"
.br
.RI "Data file\&. "
.ti -1c
.RI "\fB$id\fP"
.br
.RI "Document identifier\&. "
.ti -1c
.RI "\fB$document\fP =[]"
.br
.RI "Document contents\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBfactory\fP ($id, $row)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$db\fP"
.br
.RI "Flat-file \fBDB\fP wrapper\&. "
.in -1c
.SH "Detailed Description"
.PP 
Flat-file \fBDB\fP mapper\&. 
.PP
Definition at line 26 of file mapper\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\\\fBDB\\Jig\fP $db,  $file)"
Instantiate class 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$db\fP object 
.br
\fI$file\fP string 
.RE
.PP

.PP
Definition at line 470 of file mapper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "cast ( $obj = \fCNULL\fP)"
Return fields of mapper object as an associative array 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$obj\fP object 
.RE
.PP

.PP
Definition at line 111 of file mapper\&.php\&.
.SS "clear ( $key)"
Delete field 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 83 of file mapper\&.php\&.
.SS "copyfrom ( $var,  $func = \fCNULL\fP)"
Hydrate mapper object using hive array variable 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array|string 
.br
\fI$func\fP callback 
.RE
.PP

.PP
Definition at line 428 of file mapper\&.php\&.
.SS "copyto ( $key)"
Populate hive array variable with mapper fields 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 442 of file mapper\&.php\&.
.SS "count ( $filter = \fCNULL\fP,  $ttl = \fC0\fP)"
Count records that match criteria 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP array 
.br
\fI$ttl\fP int 
.RE
.PP

.PP
Definition at line 291 of file mapper\&.php\&.
.SS "dbtype ()"
Return database type 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 42 of file mapper\&.php\&.
.SS "erase ( $filter = \fCNULL\fP)"
Delete current record 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP array 
.RE
.PP

.PP
Definition at line 370 of file mapper\&.php\&.
.SS "exists ( $key)"
Return TRUE if field is defined 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 51 of file mapper\&.php\&.
.SS "factory ( $id,  $row)\fC [protected]\fP"
Convert array to mapper object 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP string 
.br
\fI$row\fP array 
.RE
.PP

.PP
Definition at line 94 of file mapper\&.php\&.
.SS "fields ()"
Return field names 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 452 of file mapper\&.php\&.
.SS "find ( $filter = \fCNULL\fP, array $options = \fCNULL\fP,  $ttl = \fC0\fP,  $log = \fCTRUE\fP)"
Return records that match criteria 
.PP
\fBReturns:\fP
.RS 4
static[]|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP array 
.br
\fI$options\fP array 
.br
\fI$ttl\fP int 
.br
\fI$log\fP bool 
.RE
.PP

.PP
Definition at line 158 of file mapper\&.php\&.
.SS "& get ( $key)"
Retrieve value of field 
.PP
\fBReturns:\fP
.RS 4
scalar|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 70 of file mapper\&.php\&.
.SS "getiterator ()"
Retrieve external iterator for fields 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP

.PP
Definition at line 460 of file mapper\&.php\&.
.SS "insert ()"
Insert new record 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 317 of file mapper\&.php\&.
.SS "reset ()"
Reset cursor 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP

.PP
Definition at line 416 of file mapper\&.php\&.
.SS "set ( $key,  $val)"
Assign value to field 
.PP
\fBReturns:\fP
.RS 4
scalar|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP scalar 
.RE
.PP

.PP
Definition at line 61 of file mapper\&.php\&.
.SS "skip ( $ofs = \fC1\fP)"
Return record at specified offset using criteria of previous \fBload()\fP call and make it active 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$ofs\fP int 
.RE
.PP

.PP
Definition at line 305 of file mapper\&.php\&.
.SS "token ( $str)"
Convert tokens in string expression to variable names 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 122 of file mapper\&.php\&.
.SS "update ()"
Update current record 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 347 of file mapper\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$db\fC [protected]\fP"

.PP
Flat-file \fBDB\fP wrapper\&. 
.PP
Definition at line 30 of file mapper\&.php\&.
.SS "$document =[]"

.PP
Document contents\&. 
.PP
Definition at line 36 of file mapper\&.php\&.
.SS "$file"

.PP
Data file\&. 
.PP
Definition at line 30 of file mapper\&.php\&.
.SS "$id"

.PP
Document identifier\&. 
.PP
Definition at line 30 of file mapper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
