.TH "DB\Mongo" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB\Mongo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMapper\fP"
.br
.RI "MongoDB mapper\&. "
.ti -1c
.RI "class \fBSession\fP"
.br
.RI "MongoDB-managed session handler\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
