.TH "DB\SQL" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB\SQL \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMapper\fP"
.br
.RI "\fBSQL\fP data mapper\&. "
.ti -1c
.RI "class \fBSession\fP"
.br
.RI "SQL-managed session handler\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
