.TH "/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/image.php" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/image.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "\fBImage\fP manipulation tools\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
