.TH "/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/index.php" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$f3\fP =require('lib/base\&.php')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$f3 =require('lib/base\&.php')"

.PP
Definition at line 4 of file index\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
