.TH "ISO" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ISO \- \fBISO\fP language/country codes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrefab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlanguages\fP ()"
.br
.ti -1c
.RI "\fBcountries\fP ()"
.br
.in -1c
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const \fBCC_af\fP ='Afghanistan'"
.br
.ti -1c
.RI "const \fBCC_ax\fP ='Åland Islands'"
.br
.ti -1c
.RI "const \fBCC_al\fP ='Albania'"
.br
.ti -1c
.RI "const \fBCC_dz\fP ='Algeria'"
.br
.ti -1c
.RI "const \fBCC_as\fP ='American Samoa'"
.br
.ti -1c
.RI "const \fBCC_ad\fP ='Andorra'"
.br
.ti -1c
.RI "const \fBCC_ao\fP ='Angola'"
.br
.ti -1c
.RI "const \fBCC_ai\fP ='Anguilla'"
.br
.ti -1c
.RI "const \fBCC_aq\fP ='Antarctica'"
.br
.ti -1c
.RI "const \fBCC_ag\fP ='Antigua and Barbuda'"
.br
.ti -1c
.RI "const \fBCC_ar\fP ='Argentina'"
.br
.ti -1c
.RI "const \fBCC_am\fP ='Armenia'"
.br
.ti -1c
.RI "const \fBCC_aw\fP ='Aruba'"
.br
.ti -1c
.RI "const \fBCC_au\fP ='Australia'"
.br
.ti -1c
.RI "const \fBCC_at\fP ='Austria'"
.br
.ti -1c
.RI "const \fBCC_az\fP ='Azerbaijan'"
.br
.ti -1c
.RI "const \fBCC_bs\fP ='Bahamas'"
.br
.ti -1c
.RI "const \fBCC_bh\fP ='Bahrain'"
.br
.ti -1c
.RI "const \fBCC_bd\fP ='Bangladesh'"
.br
.ti -1c
.RI "const \fBCC_bb\fP ='Barbados'"
.br
.ti -1c
.RI "const \fBCC_by\fP ='Belarus'"
.br
.ti -1c
.RI "const \fBCC_be\fP ='Belgium'"
.br
.ti -1c
.RI "const \fBCC_bz\fP ='Belize'"
.br
.ti -1c
.RI "const \fBCC_bj\fP ='Benin'"
.br
.ti -1c
.RI "const \fBCC_bm\fP ='Bermuda'"
.br
.ti -1c
.RI "const \fBCC_bt\fP ='Bhutan'"
.br
.ti -1c
.RI "const \fBCC_bo\fP ='Bolivia'"
.br
.ti -1c
.RI "const \fBCC_bq\fP ='Bonaire, Sint Eustatius and Saba'"
.br
.ti -1c
.RI "const \fBCC_ba\fP ='Bosnia and Herzegovina'"
.br
.ti -1c
.RI "const \fBCC_bw\fP ='Botswana'"
.br
.ti -1c
.RI "const \fBCC_bv\fP ='Bouvet Island'"
.br
.ti -1c
.RI "const \fBCC_br\fP ='Brazil'"
.br
.ti -1c
.RI "const \fBCC_io\fP ='British Indian Ocean Territory'"
.br
.ti -1c
.RI "const \fBCC_bn\fP ='Brunei Darussalam'"
.br
.ti -1c
.RI "const \fBCC_bg\fP ='Bulgaria'"
.br
.ti -1c
.RI "const \fBCC_bf\fP ='Burkina Faso'"
.br
.ti -1c
.RI "const \fBCC_bi\fP ='Burundi'"
.br
.ti -1c
.RI "const \fBCC_kh\fP ='Cambodia'"
.br
.ti -1c
.RI "const \fBCC_cm\fP ='Cameroon'"
.br
.ti -1c
.RI "const \fBCC_ca\fP ='Canada'"
.br
.ti -1c
.RI "const \fBCC_cv\fP ='Cape Verde'"
.br
.ti -1c
.RI "const \fBCC_ky\fP ='Cayman Islands'"
.br
.ti -1c
.RI "const \fBCC_cf\fP ='Central African Republic'"
.br
.ti -1c
.RI "const \fBCC_td\fP ='Chad'"
.br
.ti -1c
.RI "const \fBCC_cl\fP ='Chile'"
.br
.ti -1c
.RI "const \fBCC_cn\fP ='China'"
.br
.ti -1c
.RI "const \fBCC_cx\fP ='Christmas Island'"
.br
.ti -1c
.RI "const \fBCC_cc\fP ='Cocos (Keeling) Islands'"
.br
.ti -1c
.RI "const \fBCC_co\fP ='Colombia'"
.br
.ti -1c
.RI "const \fBCC_km\fP ='Comoros'"
.br
.ti -1c
.RI "const \fBCC_cg\fP ='Congo'"
.br
.ti -1c
.RI "const \fBCC_cd\fP ='Congo, The Democratic Republic of'"
.br
.ti -1c
.RI "const \fBCC_ck\fP ='Cook Islands'"
.br
.ti -1c
.RI "const \fBCC_cr\fP ='Costa Rica'"
.br
.ti -1c
.RI "const \fBCC_ci\fP ='Côte d\\'ivoire'"
.br
.ti -1c
.RI "const \fBCC_hr\fP ='Croatia'"
.br
.ti -1c
.RI "const \fBCC_cu\fP ='Cuba'"
.br
.ti -1c
.RI "const \fBCC_cw\fP ='Curaçao'"
.br
.ti -1c
.RI "const \fBCC_cy\fP ='Cyprus'"
.br
.ti -1c
.RI "const \fBCC_cz\fP ='Czech Republic'"
.br
.ti -1c
.RI "const \fBCC_dk\fP ='Denmark'"
.br
.ti -1c
.RI "const \fBCC_dj\fP ='Djibouti'"
.br
.ti -1c
.RI "const \fBCC_dm\fP ='Dominica'"
.br
.ti -1c
.RI "const \fBCC_do\fP ='Dominican Republic'"
.br
.ti -1c
.RI "const \fBCC_ec\fP ='Ecuador'"
.br
.ti -1c
.RI "const \fBCC_eg\fP ='Egypt'"
.br
.ti -1c
.RI "const \fBCC_sv\fP ='El Salvador'"
.br
.ti -1c
.RI "const \fBCC_gq\fP ='Equatorial Guinea'"
.br
.ti -1c
.RI "const \fBCC_er\fP ='Eritrea'"
.br
.ti -1c
.RI "const \fBCC_ee\fP ='Estonia'"
.br
.ti -1c
.RI "const \fBCC_et\fP ='Ethiopia'"
.br
.ti -1c
.RI "const \fBCC_fk\fP ='Falkland Islands (Malvinas)'"
.br
.ti -1c
.RI "const \fBCC_fo\fP ='Faroe Islands'"
.br
.ti -1c
.RI "const \fBCC_fj\fP ='Fiji'"
.br
.ti -1c
.RI "const \fBCC_fi\fP ='Finland'"
.br
.ti -1c
.RI "const \fBCC_fr\fP ='France'"
.br
.ti -1c
.RI "const \fBCC_gf\fP ='French Guiana'"
.br
.ti -1c
.RI "const \fBCC_pf\fP ='French Polynesia'"
.br
.ti -1c
.RI "const \fBCC_tf\fP ='French Southern Territories'"
.br
.ti -1c
.RI "const \fBCC_ga\fP ='Gabon'"
.br
.ti -1c
.RI "const \fBCC_gm\fP ='Gambia'"
.br
.ti -1c
.RI "const \fBCC_ge\fP ='Georgia'"
.br
.ti -1c
.RI "const \fBCC_de\fP ='Germany'"
.br
.ti -1c
.RI "const \fBCC_gh\fP ='Ghana'"
.br
.ti -1c
.RI "const \fBCC_gi\fP ='Gibraltar'"
.br
.ti -1c
.RI "const \fBCC_gr\fP ='Greece'"
.br
.ti -1c
.RI "const \fBCC_gl\fP ='Greenland'"
.br
.ti -1c
.RI "const \fBCC_gd\fP ='Grenada'"
.br
.ti -1c
.RI "const \fBCC_gp\fP ='Guadeloupe'"
.br
.ti -1c
.RI "const \fBCC_gu\fP ='Guam'"
.br
.ti -1c
.RI "const \fBCC_gt\fP ='Guatemala'"
.br
.ti -1c
.RI "const \fBCC_gg\fP ='Guernsey'"
.br
.ti -1c
.RI "const \fBCC_gn\fP ='Guinea'"
.br
.ti -1c
.RI "const \fBCC_gw\fP ='Guinea\-Bissau'"
.br
.ti -1c
.RI "const \fBCC_gy\fP ='Guyana'"
.br
.ti -1c
.RI "const \fBCC_ht\fP ='Haiti'"
.br
.ti -1c
.RI "const \fBCC_hm\fP ='Heard Island and McDonald Islands'"
.br
.ti -1c
.RI "const \fBCC_va\fP ='Holy See (Vatican City State)'"
.br
.ti -1c
.RI "const \fBCC_hn\fP ='Honduras'"
.br
.ti -1c
.RI "const \fBCC_hk\fP ='Hong Kong'"
.br
.ti -1c
.RI "const \fBCC_hu\fP ='Hungary'"
.br
.ti -1c
.RI "const \fBCC_is\fP ='Iceland'"
.br
.ti -1c
.RI "const \fBCC_in\fP ='India'"
.br
.ti -1c
.RI "const \fBCC_id\fP ='Indonesia'"
.br
.ti -1c
.RI "const \fBCC_ir\fP ='Iran, Islamic Republic of'"
.br
.ti -1c
.RI "const \fBCC_iq\fP ='Iraq'"
.br
.ti -1c
.RI "const \fBCC_ie\fP ='Ireland'"
.br
.ti -1c
.RI "const \fBCC_im\fP ='Isle of Man'"
.br
.ti -1c
.RI "const \fBCC_il\fP ='Israel'"
.br
.ti -1c
.RI "const \fBCC_it\fP ='Italy'"
.br
.ti -1c
.RI "const \fBCC_jm\fP ='Jamaica'"
.br
.ti -1c
.RI "const \fBCC_jp\fP ='Japan'"
.br
.ti -1c
.RI "const \fBCC_je\fP ='Jersey'"
.br
.ti -1c
.RI "const \fBCC_jo\fP ='Jordan'"
.br
.ti -1c
.RI "const \fBCC_kz\fP ='Kazakhstan'"
.br
.ti -1c
.RI "const \fBCC_ke\fP ='Kenya'"
.br
.ti -1c
.RI "const \fBCC_ki\fP ='Kiribati'"
.br
.ti -1c
.RI "const \fBCC_kp\fP ='Korea, Democratic People\\'s Republic of'"
.br
.ti -1c
.RI "const \fBCC_kr\fP ='Korea, Republic of'"
.br
.ti -1c
.RI "const \fBCC_kw\fP ='Kuwait'"
.br
.ti -1c
.RI "const \fBCC_kg\fP ='Kyrgyzstan'"
.br
.ti -1c
.RI "const \fBCC_la\fP ='Lao People\\'s Democratic Republic'"
.br
.ti -1c
.RI "const \fBCC_lv\fP ='Latvia'"
.br
.ti -1c
.RI "const \fBCC_lb\fP ='Lebanon'"
.br
.ti -1c
.RI "const \fBCC_ls\fP ='Lesotho'"
.br
.ti -1c
.RI "const \fBCC_lr\fP ='Liberia'"
.br
.ti -1c
.RI "const \fBCC_ly\fP ='Libya'"
.br
.ti -1c
.RI "const \fBCC_li\fP ='Liechtenstein'"
.br
.ti -1c
.RI "const \fBCC_lt\fP ='Lithuania'"
.br
.ti -1c
.RI "const \fBCC_lu\fP ='Luxembourg'"
.br
.ti -1c
.RI "const \fBCC_mo\fP ='Macao'"
.br
.ti -1c
.RI "const \fBCC_mk\fP ='Macedonia, The Former Yugoslav Republic of'"
.br
.ti -1c
.RI "const \fBCC_mg\fP ='Madagascar'"
.br
.ti -1c
.RI "const \fBCC_mw\fP ='Malawi'"
.br
.ti -1c
.RI "const \fBCC_my\fP ='Malaysia'"
.br
.ti -1c
.RI "const \fBCC_mv\fP ='Maldives'"
.br
.ti -1c
.RI "const \fBCC_ml\fP ='Mali'"
.br
.ti -1c
.RI "const \fBCC_mt\fP ='Malta'"
.br
.ti -1c
.RI "const \fBCC_mh\fP ='Marshall Islands'"
.br
.ti -1c
.RI "const \fBCC_mq\fP ='Martinique'"
.br
.ti -1c
.RI "const \fBCC_mr\fP ='Mauritania'"
.br
.ti -1c
.RI "const \fBCC_mu\fP ='Mauritius'"
.br
.ti -1c
.RI "const \fBCC_yt\fP ='Mayotte'"
.br
.ti -1c
.RI "const \fBCC_mx\fP ='Mexico'"
.br
.ti -1c
.RI "const \fBCC_fm\fP ='Micronesia, Federated States of'"
.br
.ti -1c
.RI "const \fBCC_md\fP ='Moldova, Republic of'"
.br
.ti -1c
.RI "const \fBCC_mc\fP ='Monaco'"
.br
.ti -1c
.RI "const \fBCC_mn\fP ='Mongolia'"
.br
.ti -1c
.RI "const \fBCC_me\fP ='Montenegro'"
.br
.ti -1c
.RI "const \fBCC_ms\fP ='Montserrat'"
.br
.ti -1c
.RI "const \fBCC_ma\fP ='Morocco'"
.br
.ti -1c
.RI "const \fBCC_mz\fP ='Mozambique'"
.br
.ti -1c
.RI "const \fBCC_mm\fP ='Myanmar'"
.br
.ti -1c
.RI "const \fBCC_na\fP ='Namibia'"
.br
.ti -1c
.RI "const \fBCC_nr\fP ='Nauru'"
.br
.ti -1c
.RI "const \fBCC_np\fP ='Nepal'"
.br
.ti -1c
.RI "const \fBCC_nl\fP ='Netherlands'"
.br
.ti -1c
.RI "const \fBCC_nc\fP ='New Caledonia'"
.br
.ti -1c
.RI "const \fBCC_nz\fP ='New Zealand'"
.br
.ti -1c
.RI "const \fBCC_ni\fP ='Nicaragua'"
.br
.ti -1c
.RI "const \fBCC_ne\fP ='Niger'"
.br
.ti -1c
.RI "const \fBCC_ng\fP ='Nigeria'"
.br
.ti -1c
.RI "const \fBCC_nu\fP ='Niue'"
.br
.ti -1c
.RI "const \fBCC_nf\fP ='Norfolk Island'"
.br
.ti -1c
.RI "const \fBCC_mp\fP ='Northern Mariana Islands'"
.br
.ti -1c
.RI "const \fBCC_no\fP ='Norway'"
.br
.ti -1c
.RI "const \fBCC_om\fP ='Oman'"
.br
.ti -1c
.RI "const \fBCC_pk\fP ='Pakistan'"
.br
.ti -1c
.RI "const \fBCC_pw\fP ='Palau'"
.br
.ti -1c
.RI "const \fBCC_ps\fP ='Palestinian Territory, Occupied'"
.br
.ti -1c
.RI "const \fBCC_pa\fP ='Panama'"
.br
.ti -1c
.RI "const \fBCC_pg\fP ='Papua New Guinea'"
.br
.ti -1c
.RI "const \fBCC_py\fP ='Paraguay'"
.br
.ti -1c
.RI "const \fBCC_pe\fP ='Peru'"
.br
.ti -1c
.RI "const \fBCC_ph\fP ='Philippines'"
.br
.ti -1c
.RI "const \fBCC_pn\fP ='Pitcairn'"
.br
.ti -1c
.RI "const \fBCC_pl\fP ='Poland'"
.br
.ti -1c
.RI "const \fBCC_pt\fP ='Portugal'"
.br
.ti -1c
.RI "const \fBCC_pr\fP ='Puerto Rico'"
.br
.ti -1c
.RI "const \fBCC_qa\fP ='Qatar'"
.br
.ti -1c
.RI "const \fBCC_re\fP ='Réunion'"
.br
.ti -1c
.RI "const \fBCC_ro\fP ='Romania'"
.br
.ti -1c
.RI "const \fBCC_ru\fP ='Russian Federation'"
.br
.ti -1c
.RI "const \fBCC_rw\fP ='Rwanda'"
.br
.ti -1c
.RI "const \fBCC_bl\fP ='Saint Barthélemy'"
.br
.ti -1c
.RI "const \fBCC_sh\fP ='Saint Helena, Ascension and Tristan da Cunha'"
.br
.ti -1c
.RI "const \fBCC_kn\fP ='Saint Kitts and Nevis'"
.br
.ti -1c
.RI "const \fBCC_lc\fP ='Saint Lucia'"
.br
.ti -1c
.RI "const \fBCC_mf\fP ='Saint Martin (French Part)'"
.br
.ti -1c
.RI "const \fBCC_pm\fP ='Saint Pierre and Miquelon'"
.br
.ti -1c
.RI "const \fBCC_vc\fP ='Saint Vincent and The Grenadines'"
.br
.ti -1c
.RI "const \fBCC_ws\fP ='Samoa'"
.br
.ti -1c
.RI "const \fBCC_sm\fP ='San Marino'"
.br
.ti -1c
.RI "const \fBCC_st\fP ='Sao Tome and Principe'"
.br
.ti -1c
.RI "const \fBCC_sa\fP ='Saudi Arabia'"
.br
.ti -1c
.RI "const \fBCC_sn\fP ='Senegal'"
.br
.ti -1c
.RI "const \fBCC_rs\fP ='Serbia'"
.br
.ti -1c
.RI "const \fBCC_sc\fP ='Seychelles'"
.br
.ti -1c
.RI "const \fBCC_sl\fP ='Sierra Leone'"
.br
.ti -1c
.RI "const \fBCC_sg\fP ='Singapore'"
.br
.ti -1c
.RI "const \fBCC_sk\fP ='Slovakia'"
.br
.ti -1c
.RI "const \fBCC_sx\fP ='Sint Maarten (Dutch Part)'"
.br
.ti -1c
.RI "const \fBCC_si\fP ='Slovenia'"
.br
.ti -1c
.RI "const \fBCC_sb\fP ='Solomon Islands'"
.br
.ti -1c
.RI "const \fBCC_so\fP ='Somalia'"
.br
.ti -1c
.RI "const \fBCC_za\fP ='South Africa'"
.br
.ti -1c
.RI "const \fBCC_gs\fP ='South Georgia and The South Sandwich Islands'"
.br
.ti -1c
.RI "const \fBCC_ss\fP ='South Sudan'"
.br
.ti -1c
.RI "const \fBCC_es\fP ='Spain'"
.br
.ti -1c
.RI "const \fBCC_lk\fP ='Sri Lanka'"
.br
.ti -1c
.RI "const \fBCC_sd\fP ='Sudan'"
.br
.ti -1c
.RI "const \fBCC_sr\fP ='Suriname'"
.br
.ti -1c
.RI "const \fBCC_sj\fP ='Svalbard and Jan Mayen'"
.br
.ti -1c
.RI "const \fBCC_sz\fP ='Swaziland'"
.br
.ti -1c
.RI "const \fBCC_se\fP ='Sweden'"
.br
.ti -1c
.RI "const \fBCC_ch\fP ='Switzerland'"
.br
.ti -1c
.RI "const \fBCC_sy\fP ='Syrian Arab Republic'"
.br
.ti -1c
.RI "const \fBCC_tw\fP ='Taiwan, Province of China'"
.br
.ti -1c
.RI "const \fBCC_tj\fP ='Tajikistan'"
.br
.ti -1c
.RI "const \fBCC_tz\fP ='Tanzania, United Republic of'"
.br
.ti -1c
.RI "const \fBCC_th\fP ='Thailand'"
.br
.ti -1c
.RI "const \fBCC_tl\fP ='Timor\-Leste'"
.br
.ti -1c
.RI "const \fBCC_tg\fP ='Togo'"
.br
.ti -1c
.RI "const \fBCC_tk\fP ='Tokelau'"
.br
.ti -1c
.RI "const \fBCC_to\fP ='Tonga'"
.br
.ti -1c
.RI "const \fBCC_tt\fP ='Trinidad and Tobago'"
.br
.ti -1c
.RI "const \fBCC_tn\fP ='Tunisia'"
.br
.ti -1c
.RI "const \fBCC_tr\fP ='Turkey'"
.br
.ti -1c
.RI "const \fBCC_tm\fP ='Turkmenistan'"
.br
.ti -1c
.RI "const \fBCC_tc\fP ='Turks and Caicos Islands'"
.br
.ti -1c
.RI "const \fBCC_tv\fP ='Tuvalu'"
.br
.ti -1c
.RI "const \fBCC_ug\fP ='Uganda'"
.br
.ti -1c
.RI "const \fBCC_ua\fP ='Ukraine'"
.br
.ti -1c
.RI "const \fBCC_ae\fP ='United Arab Emirates'"
.br
.ti -1c
.RI "const \fBCC_gb\fP ='United Kingdom'"
.br
.ti -1c
.RI "const \fBCC_us\fP ='United States'"
.br
.ti -1c
.RI "const \fBCC_um\fP ='United States Minor Outlying Islands'"
.br
.ti -1c
.RI "const \fBCC_uy\fP ='Uruguay'"
.br
.ti -1c
.RI "const \fBCC_uz\fP ='Uzbekistan'"
.br
.ti -1c
.RI "const \fBCC_vu\fP ='Vanuatu'"
.br
.ti -1c
.RI "const \fBCC_ve\fP ='Venezuela'"
.br
.ti -1c
.RI "const \fBCC_vn\fP ='Viet Nam'"
.br
.ti -1c
.RI "const \fBCC_vg\fP ='Virgin Islands, British'"
.br
.ti -1c
.RI "const \fBCC_vi\fP ='Virgin Islands, U\&.S\&.'"
.br
.ti -1c
.RI "const \fBCC_wf\fP ='Wallis and Futuna'"
.br
.ti -1c
.RI "const \fBCC_eh\fP ='Western Sahara'"
.br
.ti -1c
.RI "const \fBCC_ye\fP ='Yemen'"
.br
.ti -1c
.RI "const \fBCC_zm\fP ='Zambia'"
.br
.ti -1c
.RI "const \fBCC_zw\fP ='Zimbabwe'"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const \fBLC_af\fP ='Afrikaans'"
.br
.ti -1c
.RI "const \fBLC_am\fP ='Amharic'"
.br
.ti -1c
.RI "const \fBLC_ar\fP ='Arabic'"
.br
.ti -1c
.RI "const \fBLC_as\fP ='Assamese'"
.br
.ti -1c
.RI "const \fBLC_ba\fP ='Bashkir'"
.br
.ti -1c
.RI "const \fBLC_be\fP ='Belarusian'"
.br
.ti -1c
.RI "const \fBLC_bg\fP ='Bulgarian'"
.br
.ti -1c
.RI "const \fBLC_bn\fP ='Bengali'"
.br
.ti -1c
.RI "const \fBLC_bo\fP ='Tibetan'"
.br
.ti -1c
.RI "const \fBLC_br\fP ='Breton'"
.br
.ti -1c
.RI "const \fBLC_ca\fP ='Catalan'"
.br
.ti -1c
.RI "const \fBLC_co\fP ='Corsican'"
.br
.ti -1c
.RI "const \fBLC_cs\fP ='Czech'"
.br
.ti -1c
.RI "const \fBLC_cy\fP ='Welsh'"
.br
.ti -1c
.RI "const \fBLC_da\fP ='Danish'"
.br
.ti -1c
.RI "const \fBLC_de\fP ='German'"
.br
.ti -1c
.RI "const \fBLC_dv\fP ='Divehi'"
.br
.ti -1c
.RI "const \fBLC_el\fP ='Greek'"
.br
.ti -1c
.RI "const \fBLC_en\fP ='English'"
.br
.ti -1c
.RI "const \fBLC_es\fP ='Spanish'"
.br
.ti -1c
.RI "const \fBLC_et\fP ='Estonian'"
.br
.ti -1c
.RI "const \fBLC_eu\fP ='Basque'"
.br
.ti -1c
.RI "const \fBLC_fa\fP ='Persian'"
.br
.ti -1c
.RI "const \fBLC_fi\fP ='Finnish'"
.br
.ti -1c
.RI "const \fBLC_fo\fP ='Faroese'"
.br
.ti -1c
.RI "const \fBLC_fr\fP ='French'"
.br
.ti -1c
.RI "const \fBLC_gd\fP ='Scottish Gaelic'"
.br
.ti -1c
.RI "const \fBLC_gl\fP ='Galician'"
.br
.ti -1c
.RI "const \fBLC_gu\fP ='Gujarati'"
.br
.ti -1c
.RI "const \fBLC_he\fP ='Hebrew'"
.br
.ti -1c
.RI "const \fBLC_hi\fP ='Hindi'"
.br
.ti -1c
.RI "const \fBLC_hr\fP ='Croatian'"
.br
.ti -1c
.RI "const \fBLC_hu\fP ='Hungarian'"
.br
.ti -1c
.RI "const \fBLC_hy\fP ='Armenian'"
.br
.ti -1c
.RI "const \fBLC_id\fP ='Indonesian'"
.br
.ti -1c
.RI "const \fBLC_ig\fP ='Igbo'"
.br
.ti -1c
.RI "const \fBLC_is\fP ='Icelandic'"
.br
.ti -1c
.RI "const \fBLC_it\fP ='Italian'"
.br
.ti -1c
.RI "const \fBLC_ja\fP ='Japanese'"
.br
.ti -1c
.RI "const \fBLC_ka\fP ='Georgian'"
.br
.ti -1c
.RI "const \fBLC_kk\fP ='Kazakh'"
.br
.ti -1c
.RI "const \fBLC_km\fP ='Khmer'"
.br
.ti -1c
.RI "const \fBLC_kn\fP ='Kannada'"
.br
.ti -1c
.RI "const \fBLC_ko\fP ='Korean'"
.br
.ti -1c
.RI "const \fBLC_lb\fP ='Luxembourgish'"
.br
.ti -1c
.RI "const \fBLC_lo\fP ='Lao'"
.br
.ti -1c
.RI "const \fBLC_lt\fP ='Lithuanian'"
.br
.ti -1c
.RI "const \fBLC_lv\fP ='Latvian'"
.br
.ti -1c
.RI "const \fBLC_mi\fP ='Maori'"
.br
.ti -1c
.RI "const \fBLC_ml\fP ='Malayalam'"
.br
.ti -1c
.RI "const \fBLC_mr\fP ='Marathi'"
.br
.ti -1c
.RI "const \fBLC_ms\fP ='Malay'"
.br
.ti -1c
.RI "const \fBLC_mt\fP ='Maltese'"
.br
.ti -1c
.RI "const \fBLC_ne\fP ='Nepali'"
.br
.ti -1c
.RI "const \fBLC_nl\fP ='Dutch'"
.br
.ti -1c
.RI "const \fBLC_no\fP ='Norwegian'"
.br
.ti -1c
.RI "const \fBLC_oc\fP ='Occitan'"
.br
.ti -1c
.RI "const \fBLC_or\fP ='Oriya'"
.br
.ti -1c
.RI "const \fBLC_pl\fP ='Polish'"
.br
.ti -1c
.RI "const \fBLC_ps\fP ='Pashto'"
.br
.ti -1c
.RI "const \fBLC_pt\fP ='Portuguese'"
.br
.ti -1c
.RI "const \fBLC_qu\fP ='Quechua'"
.br
.ti -1c
.RI "const \fBLC_ro\fP ='Romanian'"
.br
.ti -1c
.RI "const \fBLC_ru\fP ='Russian'"
.br
.ti -1c
.RI "const \fBLC_rw\fP ='Kinyarwanda'"
.br
.ti -1c
.RI "const \fBLC_sa\fP ='Sanskrit'"
.br
.ti -1c
.RI "const \fBLC_si\fP ='Sinhala'"
.br
.ti -1c
.RI "const \fBLC_sk\fP ='Slovak'"
.br
.ti -1c
.RI "const \fBLC_sl\fP ='Slovenian'"
.br
.ti -1c
.RI "const \fBLC_sq\fP ='Albanian'"
.br
.ti -1c
.RI "const \fBLC_sv\fP ='Swedish'"
.br
.ti -1c
.RI "const \fBLC_ta\fP ='Tamil'"
.br
.ti -1c
.RI "const \fBLC_te\fP ='Telugu'"
.br
.ti -1c
.RI "const \fBLC_th\fP ='Thai'"
.br
.ti -1c
.RI "const \fBLC_tk\fP ='Turkmen'"
.br
.ti -1c
.RI "const \fBLC_tr\fP ='Turkish'"
.br
.ti -1c
.RI "const \fBLC_tt\fP ='Tatar'"
.br
.ti -1c
.RI "const \fBLC_uk\fP ='Ukrainian'"
.br
.ti -1c
.RI "const \fBLC_ur\fP ='Urdu'"
.br
.ti -1c
.RI "const \fBLC_vi\fP ='Vietnamese'"
.br
.ti -1c
.RI "const \fBLC_wo\fP ='Wolof'"
.br
.ti -1c
.RI "const \fBLC_yo\fP ='Yoruba'"
.br
.ti -1c
.RI "const \fBLC_zh\fP ='Chinese'"
.br
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBISO\fP language/country codes\&. 
.PP
Definition at line 2851 of file base\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "countries ()"
Return list of countries indexed by \fBISO\fP 3166-1 country code 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 3205 of file base\&.php\&.
.SS "languages ()"
Return list of languages indexed by \fBISO\fP 639-1 language code 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 3197 of file base\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const CC_ad ='Andorra'"

.PP
Definition at line 2860 of file base\&.php\&.
.SS "const CC_ae ='United Arab Emirates'"

.PP
Definition at line 3088 of file base\&.php\&.
.SS "const CC_af ='Afghanistan'"

.PP
Definition at line 2855 of file base\&.php\&.
.SS "const CC_ag ='Antigua and Barbuda'"

.PP
Definition at line 2864 of file base\&.php\&.
.SS "const CC_ai ='Anguilla'"

.PP
Definition at line 2862 of file base\&.php\&.
.SS "const CC_al ='Albania'"

.PP
Definition at line 2857 of file base\&.php\&.
.SS "const CC_am ='Armenia'"

.PP
Definition at line 2866 of file base\&.php\&.
.SS "const CC_ao ='Angola'"

.PP
Definition at line 2861 of file base\&.php\&.
.SS "const CC_aq ='Antarctica'"

.PP
Definition at line 2863 of file base\&.php\&.
.SS "const CC_ar ='Argentina'"

.PP
Definition at line 2865 of file base\&.php\&.
.SS "const CC_as ='American Samoa'"

.PP
Definition at line 2859 of file base\&.php\&.
.SS "const CC_at ='Austria'"

.PP
Definition at line 2869 of file base\&.php\&.
.SS "const CC_au ='Australia'"

.PP
Definition at line 2868 of file base\&.php\&.
.SS "const CC_aw ='Aruba'"

.PP
Definition at line 2867 of file base\&.php\&.
.SS "const CC_ax ='Åland Islands'"

.PP
Definition at line 2856 of file base\&.php\&.
.SS "const CC_az ='Azerbaijan'"

.PP
Definition at line 2870 of file base\&.php\&.
.SS "const CC_ba ='Bosnia and Herzegovina'"

.PP
Definition at line 2883 of file base\&.php\&.
.SS "const CC_bb ='Barbados'"

.PP
Definition at line 2874 of file base\&.php\&.
.SS "const CC_bd ='Bangladesh'"

.PP
Definition at line 2873 of file base\&.php\&.
.SS "const CC_be ='Belgium'"

.PP
Definition at line 2876 of file base\&.php\&.
.SS "const CC_bf ='Burkina Faso'"

.PP
Definition at line 2890 of file base\&.php\&.
.SS "const CC_bg ='Bulgaria'"

.PP
Definition at line 2889 of file base\&.php\&.
.SS "const CC_bh ='Bahrain'"

.PP
Definition at line 2872 of file base\&.php\&.
.SS "const CC_bi ='Burundi'"

.PP
Definition at line 2891 of file base\&.php\&.
.SS "const CC_bj ='Benin'"

.PP
Definition at line 2878 of file base\&.php\&.
.SS "const CC_bl ='Saint Barthélemy'"

.PP
Definition at line 3039 of file base\&.php\&.
.SS "const CC_bm ='Bermuda'"

.PP
Definition at line 2879 of file base\&.php\&.
.SS "const CC_bn ='Brunei Darussalam'"

.PP
Definition at line 2888 of file base\&.php\&.
.SS "const CC_bo ='Bolivia'"

.PP
Definition at line 2881 of file base\&.php\&.
.SS "const CC_bq ='Bonaire, Sint Eustatius and Saba'"

.PP
Definition at line 2882 of file base\&.php\&.
.SS "const CC_br ='Brazil'"

.PP
Definition at line 2886 of file base\&.php\&.
.SS "const CC_bs ='Bahamas'"

.PP
Definition at line 2871 of file base\&.php\&.
.SS "const CC_bt ='Bhutan'"

.PP
Definition at line 2880 of file base\&.php\&.
.SS "const CC_bv ='Bouvet Island'"

.PP
Definition at line 2885 of file base\&.php\&.
.SS "const CC_bw ='Botswana'"

.PP
Definition at line 2884 of file base\&.php\&.
.SS "const CC_by ='Belarus'"

.PP
Definition at line 2875 of file base\&.php\&.
.SS "const CC_bz ='Belize'"

.PP
Definition at line 2877 of file base\&.php\&.
.SS "const CC_ca ='Canada'"

.PP
Definition at line 2894 of file base\&.php\&.
.SS "const CC_cc ='Cocos (Keeling) Islands'"

.PP
Definition at line 2902 of file base\&.php\&.
.SS "const CC_cd ='Congo, The Democratic Republic of'"

.PP
Definition at line 2906 of file base\&.php\&.
.SS "const CC_cf ='Central African Republic'"

.PP
Definition at line 2897 of file base\&.php\&.
.SS "const CC_cg ='Congo'"

.PP
Definition at line 2905 of file base\&.php\&.
.SS "const CC_ch ='Switzerland'"

.PP
Definition at line 3070 of file base\&.php\&.
.SS "const CC_ci ='Côte d\\'ivoire'"

.PP
Definition at line 2909 of file base\&.php\&.
.SS "const CC_ck ='Cook Islands'"

.PP
Definition at line 2907 of file base\&.php\&.
.SS "const CC_cl ='Chile'"

.PP
Definition at line 2899 of file base\&.php\&.
.SS "const CC_cm ='Cameroon'"

.PP
Definition at line 2893 of file base\&.php\&.
.SS "const CC_cn ='China'"

.PP
Definition at line 2900 of file base\&.php\&.
.SS "const CC_co ='Colombia'"

.PP
Definition at line 2903 of file base\&.php\&.
.SS "const CC_cr ='Costa Rica'"

.PP
Definition at line 2908 of file base\&.php\&.
.SS "const CC_cu ='Cuba'"

.PP
Definition at line 2911 of file base\&.php\&.
.SS "const CC_cv ='Cape Verde'"

.PP
Definition at line 2895 of file base\&.php\&.
.SS "const CC_cw ='Curaçao'"

.PP
Definition at line 2912 of file base\&.php\&.
.SS "const CC_cx ='Christmas Island'"

.PP
Definition at line 2901 of file base\&.php\&.
.SS "const CC_cy ='Cyprus'"

.PP
Definition at line 2913 of file base\&.php\&.
.SS "const CC_cz ='Czech Republic'"

.PP
Definition at line 2914 of file base\&.php\&.
.SS "const CC_de ='Germany'"

.PP
Definition at line 2937 of file base\&.php\&.
.SS "const CC_dj ='Djibouti'"

.PP
Definition at line 2916 of file base\&.php\&.
.SS "const CC_dk ='Denmark'"

.PP
Definition at line 2915 of file base\&.php\&.
.SS "const CC_dm ='Dominica'"

.PP
Definition at line 2917 of file base\&.php\&.
.SS "const CC_do ='Dominican Republic'"

.PP
Definition at line 2918 of file base\&.php\&.
.SS "const CC_dz ='Algeria'"

.PP
Definition at line 2858 of file base\&.php\&.
.SS "const CC_ec ='Ecuador'"

.PP
Definition at line 2919 of file base\&.php\&.
.SS "const CC_ee ='Estonia'"

.PP
Definition at line 2924 of file base\&.php\&.
.SS "const CC_eg ='Egypt'"

.PP
Definition at line 2920 of file base\&.php\&.
.SS "const CC_eh ='Western Sahara'"

.PP
Definition at line 3100 of file base\&.php\&.
.SS "const CC_er ='Eritrea'"

.PP
Definition at line 2923 of file base\&.php\&.
.SS "const CC_es ='Spain'"

.PP
Definition at line 3063 of file base\&.php\&.
.SS "const CC_et ='Ethiopia'"

.PP
Definition at line 2925 of file base\&.php\&.
.SS "const CC_fi ='Finland'"

.PP
Definition at line 2929 of file base\&.php\&.
.SS "const CC_fj ='Fiji'"

.PP
Definition at line 2928 of file base\&.php\&.
.SS "const CC_fk ='Falkland Islands (Malvinas)'"

.PP
Definition at line 2926 of file base\&.php\&.
.SS "const CC_fm ='Micronesia, Federated States of'"

.PP
Definition at line 2999 of file base\&.php\&.
.SS "const CC_fo ='Faroe Islands'"

.PP
Definition at line 2927 of file base\&.php\&.
.SS "const CC_fr ='France'"

.PP
Definition at line 2930 of file base\&.php\&.
.SS "const CC_ga ='Gabon'"

.PP
Definition at line 2934 of file base\&.php\&.
.SS "const CC_gb ='United Kingdom'"

.PP
Definition at line 3089 of file base\&.php\&.
.SS "const CC_gd ='Grenada'"

.PP
Definition at line 2942 of file base\&.php\&.
.SS "const CC_ge ='Georgia'"

.PP
Definition at line 2936 of file base\&.php\&.
.SS "const CC_gf ='French Guiana'"

.PP
Definition at line 2931 of file base\&.php\&.
.SS "const CC_gg ='Guernsey'"

.PP
Definition at line 2946 of file base\&.php\&.
.SS "const CC_gh ='Ghana'"

.PP
Definition at line 2938 of file base\&.php\&.
.SS "const CC_gi ='Gibraltar'"

.PP
Definition at line 2939 of file base\&.php\&.
.SS "const CC_gl ='Greenland'"

.PP
Definition at line 2941 of file base\&.php\&.
.SS "const CC_gm ='Gambia'"

.PP
Definition at line 2935 of file base\&.php\&.
.SS "const CC_gn ='Guinea'"

.PP
Definition at line 2947 of file base\&.php\&.
.SS "const CC_gp ='Guadeloupe'"

.PP
Definition at line 2943 of file base\&.php\&.
.SS "const CC_gq ='Equatorial Guinea'"

.PP
Definition at line 2922 of file base\&.php\&.
.SS "const CC_gr ='Greece'"

.PP
Definition at line 2940 of file base\&.php\&.
.SS "const CC_gs ='South Georgia and The South Sandwich Islands'"

.PP
Definition at line 3061 of file base\&.php\&.
.SS "const CC_gt ='Guatemala'"

.PP
Definition at line 2945 of file base\&.php\&.
.SS "const CC_gu ='Guam'"

.PP
Definition at line 2944 of file base\&.php\&.
.SS "const CC_gw ='Guinea\-Bissau'"

.PP
Definition at line 2948 of file base\&.php\&.
.SS "const CC_gy ='Guyana'"

.PP
Definition at line 2949 of file base\&.php\&.
.SS "const CC_hk ='Hong Kong'"

.PP
Definition at line 2954 of file base\&.php\&.
.SS "const CC_hm ='Heard Island and McDonald Islands'"

.PP
Definition at line 2951 of file base\&.php\&.
.SS "const CC_hn ='Honduras'"

.PP
Definition at line 2953 of file base\&.php\&.
.SS "const CC_hr ='Croatia'"

.PP
Definition at line 2910 of file base\&.php\&.
.SS "const CC_ht ='Haiti'"

.PP
Definition at line 2950 of file base\&.php\&.
.SS "const CC_hu ='Hungary'"

.PP
Definition at line 2955 of file base\&.php\&.
.SS "const CC_id ='Indonesia'"

.PP
Definition at line 2958 of file base\&.php\&.
.SS "const CC_ie ='Ireland'"

.PP
Definition at line 2961 of file base\&.php\&.
.SS "const CC_il ='Israel'"

.PP
Definition at line 2963 of file base\&.php\&.
.SS "const CC_im ='Isle of Man'"

.PP
Definition at line 2962 of file base\&.php\&.
.SS "const CC_in ='India'"

.PP
Definition at line 2957 of file base\&.php\&.
.SS "const CC_io ='British Indian Ocean Territory'"

.PP
Definition at line 2887 of file base\&.php\&.
.SS "const CC_iq ='Iraq'"

.PP
Definition at line 2960 of file base\&.php\&.
.SS "const CC_ir ='Iran, Islamic Republic of'"

.PP
Definition at line 2959 of file base\&.php\&.
.SS "const CC_is ='Iceland'"

.PP
Definition at line 2956 of file base\&.php\&.
.SS "const CC_it ='Italy'"

.PP
Definition at line 2964 of file base\&.php\&.
.SS "const CC_je ='Jersey'"

.PP
Definition at line 2967 of file base\&.php\&.
.SS "const CC_jm ='Jamaica'"

.PP
Definition at line 2965 of file base\&.php\&.
.SS "const CC_jo ='Jordan'"

.PP
Definition at line 2968 of file base\&.php\&.
.SS "const CC_jp ='Japan'"

.PP
Definition at line 2966 of file base\&.php\&.
.SS "const CC_ke ='Kenya'"

.PP
Definition at line 2970 of file base\&.php\&.
.SS "const CC_kg ='Kyrgyzstan'"

.PP
Definition at line 2975 of file base\&.php\&.
.SS "const CC_kh ='Cambodia'"

.PP
Definition at line 2892 of file base\&.php\&.
.SS "const CC_ki ='Kiribati'"

.PP
Definition at line 2971 of file base\&.php\&.
.SS "const CC_km ='Comoros'"

.PP
Definition at line 2904 of file base\&.php\&.
.SS "const CC_kn ='Saint Kitts and Nevis'"

.PP
Definition at line 3041 of file base\&.php\&.
.SS "const CC_kp ='Korea, Democratic People\\'s Republic of'"

.PP
Definition at line 2972 of file base\&.php\&.
.SS "const CC_kr ='Korea, Republic of'"

.PP
Definition at line 2973 of file base\&.php\&.
.SS "const CC_kw ='Kuwait'"

.PP
Definition at line 2974 of file base\&.php\&.
.SS "const CC_ky ='Cayman Islands'"

.PP
Definition at line 2896 of file base\&.php\&.
.SS "const CC_kz ='Kazakhstan'"

.PP
Definition at line 2969 of file base\&.php\&.
.SS "const CC_la ='Lao People\\'s Democratic Republic'"

.PP
Definition at line 2976 of file base\&.php\&.
.SS "const CC_lb ='Lebanon'"

.PP
Definition at line 2978 of file base\&.php\&.
.SS "const CC_lc ='Saint Lucia'"

.PP
Definition at line 3042 of file base\&.php\&.
.SS "const CC_li ='Liechtenstein'"

.PP
Definition at line 2982 of file base\&.php\&.
.SS "const CC_lk ='Sri Lanka'"

.PP
Definition at line 3064 of file base\&.php\&.
.SS "const CC_lr ='Liberia'"

.PP
Definition at line 2980 of file base\&.php\&.
.SS "const CC_ls ='Lesotho'"

.PP
Definition at line 2979 of file base\&.php\&.
.SS "const CC_lt ='Lithuania'"

.PP
Definition at line 2983 of file base\&.php\&.
.SS "const CC_lu ='Luxembourg'"

.PP
Definition at line 2984 of file base\&.php\&.
.SS "const CC_lv ='Latvia'"

.PP
Definition at line 2977 of file base\&.php\&.
.SS "const CC_ly ='Libya'"

.PP
Definition at line 2981 of file base\&.php\&.
.SS "const CC_ma ='Morocco'"

.PP
Definition at line 3005 of file base\&.php\&.
.SS "const CC_mc ='Monaco'"

.PP
Definition at line 3001 of file base\&.php\&.
.SS "const CC_md ='Moldova, Republic of'"

.PP
Definition at line 3000 of file base\&.php\&.
.SS "const CC_me ='Montenegro'"

.PP
Definition at line 3003 of file base\&.php\&.
.SS "const CC_mf ='Saint Martin (French Part)'"

.PP
Definition at line 3043 of file base\&.php\&.
.SS "const CC_mg ='Madagascar'"

.PP
Definition at line 2987 of file base\&.php\&.
.SS "const CC_mh ='Marshall Islands'"

.PP
Definition at line 2993 of file base\&.php\&.
.SS "const CC_mk ='Macedonia, The Former Yugoslav Republic of'"

.PP
Definition at line 2986 of file base\&.php\&.
.SS "const CC_ml ='Mali'"

.PP
Definition at line 2991 of file base\&.php\&.
.SS "const CC_mm ='Myanmar'"

.PP
Definition at line 3007 of file base\&.php\&.
.SS "const CC_mn ='Mongolia'"

.PP
Definition at line 3002 of file base\&.php\&.
.SS "const CC_mo ='Macao'"

.PP
Definition at line 2985 of file base\&.php\&.
.SS "const CC_mp ='Northern Mariana Islands'"

.PP
Definition at line 3019 of file base\&.php\&.
.SS "const CC_mq ='Martinique'"

.PP
Definition at line 2994 of file base\&.php\&.
.SS "const CC_mr ='Mauritania'"

.PP
Definition at line 2995 of file base\&.php\&.
.SS "const CC_ms ='Montserrat'"

.PP
Definition at line 3004 of file base\&.php\&.
.SS "const CC_mt ='Malta'"

.PP
Definition at line 2992 of file base\&.php\&.
.SS "const CC_mu ='Mauritius'"

.PP
Definition at line 2996 of file base\&.php\&.
.SS "const CC_mv ='Maldives'"

.PP
Definition at line 2990 of file base\&.php\&.
.SS "const CC_mw ='Malawi'"

.PP
Definition at line 2988 of file base\&.php\&.
.SS "const CC_mx ='Mexico'"

.PP
Definition at line 2998 of file base\&.php\&.
.SS "const CC_my ='Malaysia'"

.PP
Definition at line 2989 of file base\&.php\&.
.SS "const CC_mz ='Mozambique'"

.PP
Definition at line 3006 of file base\&.php\&.
.SS "const CC_na ='Namibia'"

.PP
Definition at line 3008 of file base\&.php\&.
.SS "const CC_nc ='New Caledonia'"

.PP
Definition at line 3012 of file base\&.php\&.
.SS "const CC_ne ='Niger'"

.PP
Definition at line 3015 of file base\&.php\&.
.SS "const CC_nf ='Norfolk Island'"

.PP
Definition at line 3018 of file base\&.php\&.
.SS "const CC_ng ='Nigeria'"

.PP
Definition at line 3016 of file base\&.php\&.
.SS "const CC_ni ='Nicaragua'"

.PP
Definition at line 3014 of file base\&.php\&.
.SS "const CC_nl ='Netherlands'"

.PP
Definition at line 3011 of file base\&.php\&.
.SS "const CC_no ='Norway'"

.PP
Definition at line 3020 of file base\&.php\&.
.SS "const CC_np ='Nepal'"

.PP
Definition at line 3010 of file base\&.php\&.
.SS "const CC_nr ='Nauru'"

.PP
Definition at line 3009 of file base\&.php\&.
.SS "const CC_nu ='Niue'"

.PP
Definition at line 3017 of file base\&.php\&.
.SS "const CC_nz ='New Zealand'"

.PP
Definition at line 3013 of file base\&.php\&.
.SS "const CC_om ='Oman'"

.PP
Definition at line 3021 of file base\&.php\&.
.SS "const CC_pa ='Panama'"

.PP
Definition at line 3025 of file base\&.php\&.
.SS "const CC_pe ='Peru'"

.PP
Definition at line 3028 of file base\&.php\&.
.SS "const CC_pf ='French Polynesia'"

.PP
Definition at line 2932 of file base\&.php\&.
.SS "const CC_pg ='Papua New Guinea'"

.PP
Definition at line 3026 of file base\&.php\&.
.SS "const CC_ph ='Philippines'"

.PP
Definition at line 3029 of file base\&.php\&.
.SS "const CC_pk ='Pakistan'"

.PP
Definition at line 3022 of file base\&.php\&.
.SS "const CC_pl ='Poland'"

.PP
Definition at line 3031 of file base\&.php\&.
.SS "const CC_pm ='Saint Pierre and Miquelon'"

.PP
Definition at line 3044 of file base\&.php\&.
.SS "const CC_pn ='Pitcairn'"

.PP
Definition at line 3030 of file base\&.php\&.
.SS "const CC_pr ='Puerto Rico'"

.PP
Definition at line 3033 of file base\&.php\&.
.SS "const CC_ps ='Palestinian Territory, Occupied'"

.PP
Definition at line 3024 of file base\&.php\&.
.SS "const CC_pt ='Portugal'"

.PP
Definition at line 3032 of file base\&.php\&.
.SS "const CC_pw ='Palau'"

.PP
Definition at line 3023 of file base\&.php\&.
.SS "const CC_py ='Paraguay'"

.PP
Definition at line 3027 of file base\&.php\&.
.SS "const CC_qa ='Qatar'"

.PP
Definition at line 3034 of file base\&.php\&.
.SS "const CC_re ='Réunion'"

.PP
Definition at line 3035 of file base\&.php\&.
.SS "const CC_ro ='Romania'"

.PP
Definition at line 3036 of file base\&.php\&.
.SS "const CC_rs ='Serbia'"

.PP
Definition at line 3051 of file base\&.php\&.
.SS "const CC_ru ='Russian Federation'"

.PP
Definition at line 3037 of file base\&.php\&.
.SS "const CC_rw ='Rwanda'"

.PP
Definition at line 3038 of file base\&.php\&.
.SS "const CC_sa ='Saudi Arabia'"

.PP
Definition at line 3049 of file base\&.php\&.
.SS "const CC_sb ='Solomon Islands'"

.PP
Definition at line 3058 of file base\&.php\&.
.SS "const CC_sc ='Seychelles'"

.PP
Definition at line 3052 of file base\&.php\&.
.SS "const CC_sd ='Sudan'"

.PP
Definition at line 3065 of file base\&.php\&.
.SS "const CC_se ='Sweden'"

.PP
Definition at line 3069 of file base\&.php\&.
.SS "const CC_sg ='Singapore'"

.PP
Definition at line 3054 of file base\&.php\&.
.SS "const CC_sh ='Saint Helena, Ascension and Tristan da Cunha'"

.PP
Definition at line 3040 of file base\&.php\&.
.SS "const CC_si ='Slovenia'"

.PP
Definition at line 3057 of file base\&.php\&.
.SS "const CC_sj ='Svalbard and Jan Mayen'"

.PP
Definition at line 3067 of file base\&.php\&.
.SS "const CC_sk ='Slovakia'"

.PP
Definition at line 3055 of file base\&.php\&.
.SS "const CC_sl ='Sierra Leone'"

.PP
Definition at line 3053 of file base\&.php\&.
.SS "const CC_sm ='San Marino'"

.PP
Definition at line 3047 of file base\&.php\&.
.SS "const CC_sn ='Senegal'"

.PP
Definition at line 3050 of file base\&.php\&.
.SS "const CC_so ='Somalia'"

.PP
Definition at line 3059 of file base\&.php\&.
.SS "const CC_sr ='Suriname'"

.PP
Definition at line 3066 of file base\&.php\&.
.SS "const CC_ss ='South Sudan'"

.PP
Definition at line 3062 of file base\&.php\&.
.SS "const CC_st ='Sao Tome and Principe'"

.PP
Definition at line 3048 of file base\&.php\&.
.SS "const CC_sv ='El Salvador'"

.PP
Definition at line 2921 of file base\&.php\&.
.SS "const CC_sx ='Sint Maarten (Dutch Part)'"

.PP
Definition at line 3056 of file base\&.php\&.
.SS "const CC_sy ='Syrian Arab Republic'"

.PP
Definition at line 3071 of file base\&.php\&.
.SS "const CC_sz ='Swaziland'"

.PP
Definition at line 3068 of file base\&.php\&.
.SS "const CC_tc ='Turks and Caicos Islands'"

.PP
Definition at line 3084 of file base\&.php\&.
.SS "const CC_td ='Chad'"

.PP
Definition at line 2898 of file base\&.php\&.
.SS "const CC_tf ='French Southern Territories'"

.PP
Definition at line 2933 of file base\&.php\&.
.SS "const CC_tg ='Togo'"

.PP
Definition at line 3077 of file base\&.php\&.
.SS "const CC_th ='Thailand'"

.PP
Definition at line 3075 of file base\&.php\&.
.SS "const CC_tj ='Tajikistan'"

.PP
Definition at line 3073 of file base\&.php\&.
.SS "const CC_tk ='Tokelau'"

.PP
Definition at line 3078 of file base\&.php\&.
.SS "const CC_tl ='Timor\-Leste'"

.PP
Definition at line 3076 of file base\&.php\&.
.SS "const CC_tm ='Turkmenistan'"

.PP
Definition at line 3083 of file base\&.php\&.
.SS "const CC_tn ='Tunisia'"

.PP
Definition at line 3081 of file base\&.php\&.
.SS "const CC_to ='Tonga'"

.PP
Definition at line 3079 of file base\&.php\&.
.SS "const CC_tr ='Turkey'"

.PP
Definition at line 3082 of file base\&.php\&.
.SS "const CC_tt ='Trinidad and Tobago'"

.PP
Definition at line 3080 of file base\&.php\&.
.SS "const CC_tv ='Tuvalu'"

.PP
Definition at line 3085 of file base\&.php\&.
.SS "const CC_tw ='Taiwan, Province of China'"

.PP
Definition at line 3072 of file base\&.php\&.
.SS "const CC_tz ='Tanzania, United Republic of'"

.PP
Definition at line 3074 of file base\&.php\&.
.SS "const CC_ua ='Ukraine'"

.PP
Definition at line 3087 of file base\&.php\&.
.SS "const CC_ug ='Uganda'"

.PP
Definition at line 3086 of file base\&.php\&.
.SS "const CC_um ='United States Minor Outlying Islands'"

.PP
Definition at line 3091 of file base\&.php\&.
.SS "const CC_us ='United States'"

.PP
Definition at line 3090 of file base\&.php\&.
.SS "const CC_uy ='Uruguay'"

.PP
Definition at line 3092 of file base\&.php\&.
.SS "const CC_uz ='Uzbekistan'"

.PP
Definition at line 3093 of file base\&.php\&.
.SS "const CC_va ='Holy See (Vatican City State)'"

.PP
Definition at line 2952 of file base\&.php\&.
.SS "const CC_vc ='Saint Vincent and The Grenadines'"

.PP
Definition at line 3045 of file base\&.php\&.
.SS "const CC_ve ='Venezuela'"

.PP
Definition at line 3095 of file base\&.php\&.
.SS "const CC_vg ='Virgin Islands, British'"

.PP
Definition at line 3097 of file base\&.php\&.
.SS "const CC_vi ='Virgin Islands, U\&.S\&.'"

.PP
Definition at line 3098 of file base\&.php\&.
.SS "const CC_vn ='Viet Nam'"

.PP
Definition at line 3096 of file base\&.php\&.
.SS "const CC_vu ='Vanuatu'"

.PP
Definition at line 3094 of file base\&.php\&.
.SS "const CC_wf ='Wallis and Futuna'"

.PP
Definition at line 3099 of file base\&.php\&.
.SS "const CC_ws ='Samoa'"

.PP
Definition at line 3046 of file base\&.php\&.
.SS "const CC_ye ='Yemen'"

.PP
Definition at line 3101 of file base\&.php\&.
.SS "const CC_yt ='Mayotte'"

.PP
Definition at line 2997 of file base\&.php\&.
.SS "const CC_za ='South Africa'"

.PP
Definition at line 3060 of file base\&.php\&.
.SS "const CC_zm ='Zambia'"

.PP
Definition at line 3102 of file base\&.php\&.
.SS "const CC_zw ='Zimbabwe'"

.PP
Definition at line 3103 of file base\&.php\&.
.SS "const LC_af ='Afrikaans'"

.PP
Definition at line 3108 of file base\&.php\&.
.SS "const LC_am ='Amharic'"

.PP
Definition at line 3109 of file base\&.php\&.
.SS "const LC_ar ='Arabic'"

.PP
Definition at line 3110 of file base\&.php\&.
.SS "const LC_as ='Assamese'"

.PP
Definition at line 3111 of file base\&.php\&.
.SS "const LC_ba ='Bashkir'"

.PP
Definition at line 3112 of file base\&.php\&.
.SS "const LC_be ='Belarusian'"

.PP
Definition at line 3113 of file base\&.php\&.
.SS "const LC_bg ='Bulgarian'"

.PP
Definition at line 3114 of file base\&.php\&.
.SS "const LC_bn ='Bengali'"

.PP
Definition at line 3115 of file base\&.php\&.
.SS "const LC_bo ='Tibetan'"

.PP
Definition at line 3116 of file base\&.php\&.
.SS "const LC_br ='Breton'"

.PP
Definition at line 3117 of file base\&.php\&.
.SS "const LC_ca ='Catalan'"

.PP
Definition at line 3118 of file base\&.php\&.
.SS "const LC_co ='Corsican'"

.PP
Definition at line 3119 of file base\&.php\&.
.SS "const LC_cs ='Czech'"

.PP
Definition at line 3120 of file base\&.php\&.
.SS "const LC_cy ='Welsh'"

.PP
Definition at line 3121 of file base\&.php\&.
.SS "const LC_da ='Danish'"

.PP
Definition at line 3122 of file base\&.php\&.
.SS "const LC_de ='German'"

.PP
Definition at line 3123 of file base\&.php\&.
.SS "const LC_dv ='Divehi'"

.PP
Definition at line 3124 of file base\&.php\&.
.SS "const LC_el ='Greek'"

.PP
Definition at line 3125 of file base\&.php\&.
.SS "const LC_en ='English'"

.PP
Definition at line 3126 of file base\&.php\&.
.SS "const LC_es ='Spanish'"

.PP
Definition at line 3127 of file base\&.php\&.
.SS "const LC_et ='Estonian'"

.PP
Definition at line 3128 of file base\&.php\&.
.SS "const LC_eu ='Basque'"

.PP
Definition at line 3129 of file base\&.php\&.
.SS "const LC_fa ='Persian'"

.PP
Definition at line 3130 of file base\&.php\&.
.SS "const LC_fi ='Finnish'"

.PP
Definition at line 3131 of file base\&.php\&.
.SS "const LC_fo ='Faroese'"

.PP
Definition at line 3132 of file base\&.php\&.
.SS "const LC_fr ='French'"

.PP
Definition at line 3133 of file base\&.php\&.
.SS "const LC_gd ='Scottish Gaelic'"

.PP
Definition at line 3134 of file base\&.php\&.
.SS "const LC_gl ='Galician'"

.PP
Definition at line 3135 of file base\&.php\&.
.SS "const LC_gu ='Gujarati'"

.PP
Definition at line 3136 of file base\&.php\&.
.SS "const LC_he ='Hebrew'"

.PP
Definition at line 3137 of file base\&.php\&.
.SS "const LC_hi ='Hindi'"

.PP
Definition at line 3138 of file base\&.php\&.
.SS "const LC_hr ='Croatian'"

.PP
Definition at line 3139 of file base\&.php\&.
.SS "const LC_hu ='Hungarian'"

.PP
Definition at line 3140 of file base\&.php\&.
.SS "const LC_hy ='Armenian'"

.PP
Definition at line 3141 of file base\&.php\&.
.SS "const LC_id ='Indonesian'"

.PP
Definition at line 3142 of file base\&.php\&.
.SS "const LC_ig ='Igbo'"

.PP
Definition at line 3143 of file base\&.php\&.
.SS "const LC_is ='Icelandic'"

.PP
Definition at line 3144 of file base\&.php\&.
.SS "const LC_it ='Italian'"

.PP
Definition at line 3145 of file base\&.php\&.
.SS "const LC_ja ='Japanese'"

.PP
Definition at line 3146 of file base\&.php\&.
.SS "const LC_ka ='Georgian'"

.PP
Definition at line 3147 of file base\&.php\&.
.SS "const LC_kk ='Kazakh'"

.PP
Definition at line 3148 of file base\&.php\&.
.SS "const LC_km ='Khmer'"

.PP
Definition at line 3149 of file base\&.php\&.
.SS "const LC_kn ='Kannada'"

.PP
Definition at line 3150 of file base\&.php\&.
.SS "const LC_ko ='Korean'"

.PP
Definition at line 3151 of file base\&.php\&.
.SS "const LC_lb ='Luxembourgish'"

.PP
Definition at line 3152 of file base\&.php\&.
.SS "const LC_lo ='Lao'"

.PP
Definition at line 3153 of file base\&.php\&.
.SS "const LC_lt ='Lithuanian'"

.PP
Definition at line 3154 of file base\&.php\&.
.SS "const LC_lv ='Latvian'"

.PP
Definition at line 3155 of file base\&.php\&.
.SS "const LC_mi ='Maori'"

.PP
Definition at line 3156 of file base\&.php\&.
.SS "const LC_ml ='Malayalam'"

.PP
Definition at line 3157 of file base\&.php\&.
.SS "const LC_mr ='Marathi'"

.PP
Definition at line 3158 of file base\&.php\&.
.SS "const LC_ms ='Malay'"

.PP
Definition at line 3159 of file base\&.php\&.
.SS "const LC_mt ='Maltese'"

.PP
Definition at line 3160 of file base\&.php\&.
.SS "const LC_ne ='Nepali'"

.PP
Definition at line 3161 of file base\&.php\&.
.SS "const LC_nl ='Dutch'"

.PP
Definition at line 3162 of file base\&.php\&.
.SS "const LC_no ='Norwegian'"

.PP
Definition at line 3163 of file base\&.php\&.
.SS "const LC_oc ='Occitan'"

.PP
Definition at line 3164 of file base\&.php\&.
.SS "const LC_or ='Oriya'"

.PP
Definition at line 3165 of file base\&.php\&.
.SS "const LC_pl ='Polish'"

.PP
Definition at line 3166 of file base\&.php\&.
.SS "const LC_ps ='Pashto'"

.PP
Definition at line 3167 of file base\&.php\&.
.SS "const LC_pt ='Portuguese'"

.PP
Definition at line 3168 of file base\&.php\&.
.SS "const LC_qu ='Quechua'"

.PP
Definition at line 3169 of file base\&.php\&.
.SS "const LC_ro ='Romanian'"

.PP
Definition at line 3170 of file base\&.php\&.
.SS "const LC_ru ='Russian'"

.PP
Definition at line 3171 of file base\&.php\&.
.SS "const LC_rw ='Kinyarwanda'"

.PP
Definition at line 3172 of file base\&.php\&.
.SS "const LC_sa ='Sanskrit'"

.PP
Definition at line 3173 of file base\&.php\&.
.SS "const LC_si ='Sinhala'"

.PP
Definition at line 3174 of file base\&.php\&.
.SS "const LC_sk ='Slovak'"

.PP
Definition at line 3175 of file base\&.php\&.
.SS "const LC_sl ='Slovenian'"

.PP
Definition at line 3176 of file base\&.php\&.
.SS "const LC_sq ='Albanian'"

.PP
Definition at line 3177 of file base\&.php\&.
.SS "const LC_sv ='Swedish'"

.PP
Definition at line 3178 of file base\&.php\&.
.SS "const LC_ta ='Tamil'"

.PP
Definition at line 3179 of file base\&.php\&.
.SS "const LC_te ='Telugu'"

.PP
Definition at line 3180 of file base\&.php\&.
.SS "const LC_th ='Thai'"

.PP
Definition at line 3181 of file base\&.php\&.
.SS "const LC_tk ='Turkmen'"

.PP
Definition at line 3182 of file base\&.php\&.
.SS "const LC_tr ='Turkish'"

.PP
Definition at line 3183 of file base\&.php\&.
.SS "const LC_tt ='Tatar'"

.PP
Definition at line 3184 of file base\&.php\&.
.SS "const LC_uk ='Ukrainian'"

.PP
Definition at line 3185 of file base\&.php\&.
.SS "const LC_ur ='Urdu'"

.PP
Definition at line 3186 of file base\&.php\&.
.SS "const LC_vi ='Vietnamese'"

.PP
Definition at line 3187 of file base\&.php\&.
.SS "const LC_wo ='Wolof'"

.PP
Definition at line 3188 of file base\&.php\&.
.SS "const LC_yo ='Yoruba'"

.PP
Definition at line 3189 of file base\&.php\&.
.SS "const LC_zh ='Chinese'"

.PP
Definition at line 3190 of file base\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
