.TH "Log" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log \- Custom logger\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP ($text, $format='r')"
.br
.ti -1c
.RI "\fBerase\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ($file)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$file\fP"
.br
.RI "File name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Custom logger\&. 
.PP
Definition at line 24 of file log\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $file)"
Instantiate class 
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP string 
.RE
.PP

.PP
Definition at line 60 of file log\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "erase ()"
Erase log 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP

.PP
Definition at line 52 of file log\&.php\&.
.SS "write ( $text,  $format = \fC'r'\fP)"
Write specified text to log file 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$text\fP string 
.br
\fI$format\fP string 
.RE
.PP

.PP
Definition at line 36 of file log\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$file\fC [protected]\fP"

.PP
File name\&. 
.PP
Definition at line 28 of file log\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
