.TH "Matrix" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix \- Generic array utilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrefab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpick\fP (array $var, $col)"
.br
.ti -1c
.RI "\fBtranspose\fP (array &$var)"
.br
.ti -1c
.RI "\fBsort\fP (array &$var, $col, $order=SORT_ASC)"
.br
.ti -1c
.RI "\fBchangekey\fP (array &$var, $old, $new)"
.br
.ti -1c
.RI "\fBcalendar\fP ($date='now', $first=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Generic array utilities\&. 
.PP
Definition at line 24 of file matrix\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "calendar ( $date = \fC'now'\fP,  $first = \fC0\fP)"
Return month calendar of specified date, with optional setting for first day of week (0 for Sunday) 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$date\fP string 
.br
\fI$first\fP int 
.RE
.PP

.PP
Definition at line 98 of file matrix\&.php\&.
.SS "changekey (array & $var,  $old,  $new)"
Change the key of a two-dimensional array element 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array 
.br
\fI$old\fP string 
.br
\fI$new\fP string 
.RE
.PP

.PP
Definition at line 84 of file matrix\&.php\&.
.SS "pick (array $var,  $col)"
Retrieve values from a specified column of a multi-dimensional array variable 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array 
.br
\fI$col\fP mixed 
.RE
.PP

.PP
Definition at line 33 of file matrix\&.php\&.
.SS "sort (array & $var,  $col,  $order = \fCSORT_ASC\fP)"
Sort a multi-dimensional array variable on a specified column 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array 
.br
\fI$col\fP mixed 
.br
\fI$order\fP int 
.RE
.PP

.PP
Definition at line 62 of file matrix\&.php\&.
.SS "transpose (array & $var)"
Rotate a two-dimensional array variable 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP array 
.RE
.PP

.PP
Definition at line 47 of file matrix\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
