.TH "Prefab" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prefab \- Factory class for single-instance objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAudit\fP, \fBBase\fP, \fBBcrypt\fP, \fBCache\fP, \fBISO\fP, \fBMarkdown\fP, \fBMatrix\fP, \fBUTF\fP, \fBView\fP, \fBWeb\fP, \fBGeo\fP, and \fBPingback\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Factory class for single-instance objects\&. 
.PP
Definition at line 24 of file base\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static instance ()\fC [static]\fP"
Return class instance 
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 30 of file base\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
