.TH "Registry" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Registry \- Container for singular object instances\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexists\fP ($key)"
.br
.ti -1c
.RI "static \fBset\fP ($key, $obj)"
.br
.ti -1c
.RI "static \fBget\fP ($key)"
.br
.ti -1c
.RI "static \fBclear\fP ($key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container for singular object instances\&. 
.PP
Definition at line 3212 of file base\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static clear ( $key)\fC [static]\fP"
Delete object from catalog 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 3251 of file base\&.php\&.
.SS "static exists ( $key)\fC [static]\fP"
Return TRUE if object exists in catalog 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 3223 of file base\&.php\&.
.SS "static get ( $key)\fC [static]\fP"
Retrieve object from catalog 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 3242 of file base\&.php\&.
.SS "static set ( $key,  $obj)\fC [static]\fP"
Add object to catalog 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$obj\fP object 
.RE
.PP

.PP
Definition at line 3233 of file base\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
