.TH "/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/session.php" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/session.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSession\fP"
.br
.RI "Cache-based session handler\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
