.TH "UTF" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTF \- Unicode string manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrefab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstrlen\fP ($str)"
.br
.ti -1c
.RI "\fBstrrev\fP ($str)"
.br
.ti -1c
.RI "\fBstripos\fP ($stack, $needle, $ofs=0)"
.br
.ti -1c
.RI "\fBstrpos\fP ($stack, $needle, $ofs=0, $case=FALSE)"
.br
.ti -1c
.RI "\fBstristr\fP ($stack, $needle, $before=FALSE)"
.br
.ti -1c
.RI "\fBstrstr\fP ($stack, $needle, $before=FALSE, $case=FALSE)"
.br
.ti -1c
.RI "\fBsubstr\fP ($str, $start, $len=0)"
.br
.ti -1c
.RI "\fBsubstr_count\fP ($stack, $needle)"
.br
.ti -1c
.RI "\fBltrim\fP ($str)"
.br
.ti -1c
.RI "\fBrtrim\fP ($str)"
.br
.ti -1c
.RI "\fBtrim\fP ($str)"
.br
.ti -1c
.RI "\fBbom\fP ()"
.br
.ti -1c
.RI "\fBtranslate\fP ($str)"
.br
.ti -1c
.RI "\fBemojify\fP ($str)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Unicode string manager\&. 
.PP
Definition at line 24 of file utf\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "bom ()"
Return UTF-8 byte order mark 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 163 of file utf\&.php\&.
.SS "emojify ( $str)"
Translate emoji tokens to Unicode font-supported symbols 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 182 of file utf\&.php\&.
.SS "ltrim ( $str)"
Strip whitespaces from the beginning of a string 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 137 of file utf\&.php\&.
.SS "rtrim ( $str)"
Strip whitespaces from the end of a string 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 146 of file utf\&.php\&.
.SS "stripos ( $stack,  $needle,  $ofs = \fC0\fP)"
Find position of first occurrence of a string (case-insensitive) 
.PP
\fBReturns:\fP
.RS 4
int|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$stack\fP string 
.br
\fI$needle\fP string 
.br
\fI$ofs\fP int 
.RE
.PP

.PP
Definition at line 53 of file utf\&.php\&.
.SS "stristr ( $stack,  $needle,  $before = \fCFALSE\fP)"
Returns part of haystack string from the first occurrence of needle to the end of haystack (case-insensitive) 
.PP
\fBReturns:\fP
.RS 4
string|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$stack\fP string 
.br
\fI$needle\fP string 
.br
\fI$before\fP bool 
.RE
.PP

.PP
Definition at line 79 of file utf\&.php\&.
.SS "strlen ( $str)"
Get string length 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 31 of file utf\&.php\&.
.SS "strpos ( $stack,  $needle,  $ofs = \fC0\fP,  $case = \fCFALSE\fP)"
Find position of first occurrence of a string 
.PP
\fBReturns:\fP
.RS 4
int|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$stack\fP string 
.br
\fI$needle\fP string 
.br
\fI$ofs\fP int 
.br
\fI$case\fP bool 
.RE
.PP

.PP
Definition at line 65 of file utf\&.php\&.
.SS "strrev ( $str)"
Reverse a string 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 41 of file utf\&.php\&.
.SS "strstr ( $stack,  $needle,  $before = \fCFALSE\fP,  $case = \fCFALSE\fP)"
Returns part of haystack string from the first occurrence of needle to the end of haystack 
.PP
\fBReturns:\fP
.RS 4
string|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$stack\fP string 
.br
\fI$needle\fP string 
.br
\fI$before\fP bool 
.br
\fI$case\fP bool 
.RE
.PP

.PP
Definition at line 92 of file utf\&.php\&.
.SS "substr ( $str,  $start,  $len = \fC0\fP)"
Return part of a string 
.PP
\fBReturns:\fP
.RS 4
string|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.br
\fI$start\fP int 
.br
\fI$len\fP int 
.RE
.PP

.PP
Definition at line 111 of file utf\&.php\&.
.SS "substr_count ( $stack,  $needle)"
Count the number of substring occurrences 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$stack\fP string 
.br
\fI$needle\fP string 
.RE
.PP

.PP
Definition at line 126 of file utf\&.php\&.
.SS "translate ( $str)"
Convert code points to Unicode symbols 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 172 of file utf\&.php\&.
.SS "trim ( $str)"
Strip whitespaces from the beginning and end of a string 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string 
.RE
.PP

.PP
Definition at line 155 of file utf\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
