.TH "Web" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Web \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGoogle\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGeo\fP"
.br
.RI "\fBGeo\fP plug-in\&. "
.ti -1c
.RI "class \fBOAuth2\fP"
.br
.RI "Lightweight \fBOAuth2\fP client\&. "
.ti -1c
.RI "class \fBOpenID\fP"
.br
.RI "\fBOpenID\fP consumer\&. "
.ti -1c
.RI "class \fBPingback\fP"
.br
.RI "\fBPingback\fP 1\&.0 protocol (client and server) implementation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
