.TH "Geo" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Geo \- \fBGeo\fP plug-in\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrefab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtzinfo\fP ($zone)"
.br
.ti -1c
.RI "\fBlocation\fP ($ip=NULL)"
.br
.ti -1c
.RI "\fBweather\fP ($latitude, $longitude, $key)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBGeo\fP plug-in\&. 
.PP
Definition at line 26 of file geo\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "location ( $ip = \fCNULL\fP)"
Return geolocation data based on specified/auto-detected IP address 
.PP
\fBReturns:\fP
.RS 4
array|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$ip\fP string 
.RE
.PP

.PP
Definition at line 54 of file geo\&.php\&.
.SS "tzinfo ( $zone)"
Return information about specified Unix time zone 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$zone\fP string 
.RE
.PP

.PP
Definition at line 33 of file geo\&.php\&.
.SS "weather ( $latitude,  $longitude,  $key)"
Return weather data based on specified latitude/longitude 
.PP
\fBReturns:\fP
.RS 4
array|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$latitude\fP float 
.br
\fI$longitude\fP float 
.br
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 92 of file geo\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
