.TH "OAuth2" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OAuth2 \- Lightweight \fBOAuth2\fP client\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMagic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuri\fP ($endpoint)"
.br
.ti -1c
.RI "\fBrequest\fP ($\fBuri\fP, $method, $token=NULL)"
.br
.ti -1c
.RI "\fBjwt\fP ($token)"
.br
.ti -1c
.RI "\fBexists\fP ($key)"
.br
.ti -1c
.RI "\fBset\fP ($key, $val)"
.br
.ti -1c
.RI "& \fBget\fP ($key)"
.br
.ti -1c
.RI "\fBclear\fP ($key=NULL)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$args\fP =[]"
.br
.RI "Scopes and claims\&. "
.in -1c
.SH "Detailed Description"
.PP 
Lightweight \fBOAuth2\fP client\&. 
.PP
Definition at line 26 of file oauth2\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "clear ( $key = \fCNULL\fP)"
Remove scope/claim 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP

.PP
Definition at line 126 of file oauth2\&.php\&.
.SS "exists ( $key)"
Return TRUE if scope/claim exists 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 94 of file oauth2\&.php\&.
.SS "& get ( $key)"
Return value of scope/claim 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 113 of file oauth2\&.php\&.
.SS "jwt ( $token)"
Parse JSON \fBWeb\fP token 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP string 
.RE
.PP

.PP
Definition at line 76 of file oauth2\&.php\&.
.SS "request ( $uri,  $method,  $token = \fCNULL\fP)"
Send request to API/token endpoint 
.PP
\fBReturns:\fP
.RS 4
string|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP string 
.br
\fI$method\fP string 
.br
\fI$token\fP array 
.RE
.PP

.PP
Definition at line 48 of file oauth2\&.php\&.
.SS "set ( $key,  $val)"
Bind value to scope/claim 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP string 
.RE
.PP

.PP
Definition at line 104 of file oauth2\&.php\&.
.SS "uri ( $endpoint)"
Return \fBOAuth2\fP authentication URI 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$endpoint\fP string 
.RE
.PP

.PP
Definition at line 37 of file oauth2\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$args =[]\fC [protected]\fP"

.PP
Scopes and claims\&. 
.PP
Definition at line 30 of file oauth2\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
