.TH "StaticMap" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaticMap \- \fBGoogle\fP Static Maps API v2 plug-in\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__call\fP ($func, array $args)"
.br
.ti -1c
.RI "\fBdump\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBURL_Static\fP ='http://maps\&.googleapis\&.com/maps/api/staticmap'"
.br
.RI "API URL\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$query\fP =array()"
.br
.RI "Query arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGoogle\fP Static Maps API v2 plug-in\&. 
.PP
Definition at line 26 of file staticmap\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__call ( $func, array $args)"
Specify API key-value pair via magic call 
.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$func\fP string 
.br
\fI$args\fP array 
.RE
.PP

.PP
Definition at line 42 of file staticmap\&.php\&.
.SS "dump ()"
Generate map 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 51 of file staticmap\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$query =array()\fC [protected]\fP"

.PP
Query arguments\&. 
.PP
Definition at line 34 of file staticmap\&.php\&.
.SS "const URL_Static ='http://maps\&.googleapis\&.com/maps/api/staticmap'"

.PP
API URL\&. 
.PP
Definition at line 30 of file staticmap\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
