.TH "OpenID" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenID \- \fBOpenID\fP consumer\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMagic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauth\fP ($proxy=NULL, $attr=[], array $reqd=NULL)"
.br
.ti -1c
.RI "\fBverified\fP ($proxy=NULL)"
.br
.ti -1c
.RI "\fBresponse\fP ()"
.br
.ti -1c
.RI "\fBexists\fP ($key)"
.br
.ti -1c
.RI "\fBset\fP ($key, $val)"
.br
.ti -1c
.RI "& \fBget\fP ($key)"
.br
.ti -1c
.RI "\fBclear\fP ($key)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$args\fP =[]"
.br
.RI "HTTP request parameters\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdiscover\fP ($proxy)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$url\fP"
.br
.RI "\fBOpenID\fP provider endpoint URL\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBOpenID\fP consumer\&. 
.PP
Definition at line 26 of file openid\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "auth ( $proxy = \fCNULL\fP,  $attr = \fC[]\fP, array $reqd = \fCNULL\fP)"
Initiate \fBOpenID\fP authentication sequence; Return FALSE on failure or redirect to \fBOpenID\fP provider URL 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$proxy\fP string 
.br
\fI$attr\fP array 
.br
\fI$reqd\fP string|array 
.RE
.PP

.PP
Definition at line 144 of file openid\&.php\&.
.SS "clear ( $key)"
Remove \fBOpenID\fP request parameter 
.PP
\fBReturns:\fP
.RS 4
NULL 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP

.PP
Definition at line 244 of file openid\&.php\&.
.SS "discover ( $proxy)\fC [protected]\fP"
Determine \fBOpenID\fP provider 
.PP
\fBReturns:\fP
.RS 4
string|FALSE 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$proxy\fP string 
.RE
.PP

.PP
Definition at line 39 of file openid\&.php\&.
.SS "exists ( $key)"
Return TRUE if \fBOpenID\fP request parameter exists 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 212 of file openid\&.php\&.
.SS "& get ( $key)"
Return value of \fBOpenID\fP request parameter 
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.RE
.PP

.PP
Definition at line 231 of file openid\&.php\&.
.SS "response ()"
Return \fBOpenID\fP response fields 
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 203 of file openid\&.php\&.
.SS "set ( $key,  $val)"
Bind value to \fBOpenID\fP request parameter 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP string 
.br
\fI$val\fP string 
.RE
.PP

.PP
Definition at line 222 of file openid\&.php\&.
.SS "verified ( $proxy = \fCNULL\fP)"
Return TRUE if \fBOpenID\fP verification was successful 
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$proxy\fP string 
.RE
.PP

.PP
Definition at line 174 of file openid\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$args =[]"

.PP
HTTP request parameters\&. 
.PP
Definition at line 32 of file openid\&.php\&.
.SS "$url\fC [protected]\fP"

.PP
\fBOpenID\fP provider endpoint URL\&. 
.PP
Definition at line 30 of file openid\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
