.TH "Web\Google" 3 "Sun Dec 25 2016" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Web\Google \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBStaticMap\fP"
.br
.RI "\fBGoogle\fP Static Maps API v2 plug-in\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
