.TH "/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/cli/ws.php" 3 "Tue Jan 3 2017" "Version 3.6" "Fat-Free Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/aplennevaux/GITHUB/Visionary-website/src/vendor/bcosca/fatfree/lib/cli/ws.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWS\fP"
.br
.RI "RFC6455 WebSocket server\&. "
.ti -1c
.RI "class \fBAgent\fP"
.br
.RI "RFC6455 remote socket\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCLI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fat-Free Framework from the source code\&.
